m-lab/etl

- appengine/README.md
- appengine/queue.yaml
Previous PR used an .xml file.  This introduces prefered yaml file, and instructions for configuring.
r: stephen-soltesz
cc: pboothe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/2)
> Create yaml queue config and README

- cmd/etl_worker/etl_worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/5)
> Listen on all interfaces.

- appengine/queue.yaml
- cmd/task_client/task_client.go
This change adds a pull queue configuration to the queue.yaml file.
As well, this change includes a sample task queue client that inserts a given payload into the pull queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/7)
> Add "etl-pull-queue" and sample insert queue command.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/14)
> Add quotes to prevent travis dying on remote pull requests

- functions/README.md
- functions/enqueue.js
- functions/enqueue_test.js
- functions/package.json
Add functions, pulling from the repo to itself to enable travis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/13)
> S1 functions

- parser/parser.go
- parser/parser_test.go
- task/task.go
- task/task_test.go
Task object that reads from a tar file, and uses an injected parser.
Some comments, some tests, needs a bit more before merging with dev
Should MERGE after s1-parser PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/10)
> Basic Task functionality

- .travis.yml
- bq/bq_test.go
- bq/insert.go
- task/task.go
- task/task_test.go
Introduces a simple BQ inserter object.
Thanks to Ya for proof of concept that made this easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/16)
> Alpha BQ Inserter, and integration into Alpha Task

- storage/gcs.go
- storage/storage.go
- storage/storage_test.go
- task/task.go
- task/task_test.go
Not ready for review, but if  you have any helpful suggestions they would be welcome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/17)
> Utility functions for gcs tar file

- appengine/queue.yaml
- cmd/etl_worker/app.yaml
- cmd/etl_worker/etl_worker.go
- parser/parser.go
- parser/parser_test.go
- task/task.go
- task/task_test.go
Adds source file, test file, parse time, and attempt count (not yet implemented).
Also adds worker count prometheus gauge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/21)
> Add meta data to the table rows

- bq/insert.go
- task/task.go
Inserts are now combined. It's pretty rough, but rough and working is the name of the game for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/22)
> S5 combine inserts

- bq/bq_test.go
- bq/insert.go
- cmd/etl_worker/etl_worker.go
- task/task.go
Changes the Inserter interface a bit.
Also some small tweaks to inserter.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/25)
> Add timeout to Inserter

- parser/ndt.go
- parser/ndt_test.go
- parser/parser.go
- parser/parser_test.go
- task/task.go
- task/task_test.go
Change to use Parser interface so that compiler detects interface error.
Fix interface error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/27)
> fix out of sync parser interface in ndt

- bq/bq_test.go
- bq/insert.go
- fake/uploader.go
Improves handling of multi-row inserts.
Extends functionality of fake Uploader.
Improves unit tests for BQ inserter, using fake uploader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/31)
> improve inserter and bq_test

- bq/bq_test.go
- bq/insert.go
- cmd/etl_worker/etl_worker.go
- etl/etl.go
- fake/uploader.go
- parser/ndt.go
- parser/parser.go
- parser/parser_test.go
- task/task.go
- task/task_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/30)
> Change intf to etl package

- bq/bq_test.go
- bq/insert.go
- cmd/etl_worker/etl_worker.go
- etl/etl.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/32)
> Use a singleton bq client

- bq/bq_test.go
- bq/insert.go
- parser/parser.go
- parser/parser_test.go
This is just some little tweaks that came about as I was cleaning up code in preparation for disco parser.  Figured better to submit them in their own tiny PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/36)
> FNSaver -> MapSaver for general use, interface tweaks

- .travis.yml
- parser/disco.go
- parser/disco_test.go
Introduces the disco parser and unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/39)
> Disco part3

- bq/insert.go
- cmd/etl_worker/etl_worker.go
- fake/uploader.go
- metrics/metrics.go
- parser/disco_test.go
Add DurationWrapper for Inserter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/43)
> metric improvements

- bq/insert.go
- cmd/etl_worker/etl_worker.go
- etl/etl.go
- etl/globals.go
Change DataType to string, and associated other code cleanups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/44)
> Clean up DataType

- appengine/queue.yaml
Queue storage is at 86%, so make it bigger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/46)
> Allow larger queue

- bq/insert.go
- metrics/metrics.go
- parser/disco.go
- parser/ndt.go
- parser/parser.go
Fix and improve metrics:
Fix InsertionHistogram
Add TestCount
Reject very large NDT test files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/49)
> Metrics and large file rejection

- bq/insert.go
- cmd/etl_worker/etl_worker.go
- metrics/metrics.go
- parser/ndt.go
- storage/storage.go
- task/task.go
Adds WorkerState, which allows us to see which state workers get hung in, or just where they spend their time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/50)
> More metrics

- bq/insert.go
- cmd/etl_worker/etl_worker.go
- parser/ndt.go
- storage/storage.go
- task/task.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/52)
> more TaskCounts, parse 1/10th of snapshots

- .travis.yml
- appengine/queue.yaml
- appengine/queue_pusher/queue_pusher.go
- cmd/etl_worker/app-disco.yaml
- cmd/etl_worker/app-ndt.yaml
- cmd/etl_worker/app-sidestream.yaml
- cmd/etl_worker/app-traceroute.yaml
- cmd/etl_worker/etl_worker.go
- etl/globals.go
- storage/storage.go
Obviates #34 , which I will discard as soon as this is submitted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/60)
> A multiqueue implementation without baggage

- appengine/queue_pusher/queue_pusher.go
- cmd/etl_worker/etl_worker.go
- etl/etl_test.go
- etl/globals.go
Add regexp based filename validation.  Update queue_pusher and etl to use same validation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/64)
> Filename validation

- cmd/etl_worker/etl_worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/66)
> Fix WriteHeader order

- appengine/queue.yaml
- cmd/etl_worker/etl_worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/67)
> Adjust queue and inflight worker parameters.

- parser/ndt.go
- parser/ndt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/73)
> Fix some errors/omissions in regexp

- parser/ndt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/74)
> Add missing anomoly reporting

- parser/ndt_test.go
- parser/pt.go
- parser/pt_test.go
- schema/pt_schema.go
- schema/web100.go
BQ inserter for PT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/70)
> BQ inserter for PT

- parser/ndt.go
Adds actually writing the results to the web100 BQ records.
Adds IP parsing.
Adds log_time and test_id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/81)
> Meta file processing additions

- parser/parser.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/88)
> activate PT parser

- bq/insert.go
- web100/web100.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/92)
> Fix bug in web100 value parsing

- bq/bq_test.go
- bq/insert.go
- metrics/metrics.go
- parser/ndt.go
Set SkipInvalidRows, and process error messages when some inserts fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/99)
> Handle insert errors better.

- parser/ndt.go
- parser/ndt_meta.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/104)
> Add basic test for metafile parsing

- bq/insert.go
- parser/ndt.go
- parser/ndt_test.go
- schema/ndt.json
- schema/web100.go
Various additions to incorporate more (and more correct) data into the NDT table entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/107)
> Add task filename field, implement fixValues, handle timestamps.

- bq/insert.go
- metrics/metrics.go
- parser/disco.go
- parser/ndt.go
- parser/ndt_meta.go
- parser/ndt_test.go
- parser/parser.go
- parser/pt_test.go
- schema/web100.go
- task/task.go
- web100/pure.go
Some changes to log messages and counters, tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/118)
> Update NDT parser to use new Go web100 parser.

- cmd/etl_worker/etl_worker.go
Parse and report retry and exec counts (from task queue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/126)
> Add retry and execution counts

- parser/ndt.go
- schema/web100.go
Fix bug in "no meta" metrics.
Add some "anomalies" fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/134)
> Add anomolies fields and fix bug.

- parser/ndt.go
- parser/ndt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/139)
> Fix handling of local_af

- parser/ndt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/155)
> reduce spammy logs

- functions/embargo/package.json
- functions/embargo/transfer.js
Also supports testing from test-mlab-sandbox to destination-mlab-sandbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/161)
> cloud functions to move files from scraper-mlab-oti/ndt to archive-mlab-oti/ndt

- bq/insert.go
- metrics/metrics.go
- parser/pt.go
- parser/pt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/160)
> add metrics for PT

- bq/insert.go
- etl/globals.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/164)
> set the number of workers adaptively according to the test type

- parser/ndt.go
- schema/web100.go
Add some missing logging/metrics.
Switch sense of bool passes to Substitute... to make it easier to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/171)
> Add more metrics logging, onlyIfNull -> overwrite

- parser/ndt_meta.go
- parser/ndt_meta_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/173)
> Add unit test and fix bugs

- .travis.yml
- cmd/etl_worker/app-ndt-staging.yaml
This allows a different configuration for batch processing.  Probably will want something different down the road, but this gives us some flexibility for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/187)
> Add separate config for etl-ndt-staging

- appengine/queue.yaml
- cmd/etl_worker/app-traceroute.yaml
- etl/globals.go
After tuning, CPU utilization improved from 60% to 90%.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/193)
> perf tuning for PT at scale

- parser/pt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/198)
> fix crash caused by corrupted content

- storage/storage.go
- storage/storage_test.go
- task/task.go
- task/task_test.go
Bug was introduced very recently, and causes infinite loop retrying.
This adds a unit test, and fixes the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/206)
> Fix break bug.

- task/task.go
Stupid typo.  Submitting TBR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/207)
> Fix bad number 20 -> 200

- parser/disco.go
- parser/ndt.go
- parser/ndt_meta.go
- parser/ndt_meta_test.go
- parser/ndt_test.go
- parser/parser.go
- parser/pt.go
- storage/storage.go
- storage/storage_test.go
- task/task.go
- task/task_test.go
- web100/web100_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/204)
> Many small tweaks for lint/vet warnings

- functions/embargo/README.md
- functions/embargo/transfer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/219)
> Embargo deploy

- parser/ss.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/223)
> add metrics

- schema/metadata_schema.go
- schema/pt_schema.go
Yes, it's very small, but it felt like this was a good subsection to check if you had any comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/220)
> Created the structs to hold the metadata.

- schema/metadata_schema.go
- schema/pt_schema.go
Schema changes for PT geolocation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/228)
> Made the schema changes.

- parser/metadata.go
- parser/metadata_test.go
2nd time submitting the PR because of Git mistakes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/229)
> PT Specific Functions --- Attempt 2

- parser/metadata.go
- parser/metadata_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/227)
> SS functions for annotation

- parser/metadata.go
- parser/metadata_test.go
- schema/metadata_schema.go
Create the code to make the parser properly nullify values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/231)
> Pt sandbox jm make null

- schema/metadata_schema.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/232)
> I think I'm starting to hate the json library. Removed spaces.

- parser/metadata.go
- parser/metadata_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/233)
> Added the batch request base code.

- parser/metadata.go
- parser/metadata_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/234)
> Added the NDT code and tests.

- parser/metadata.go
- parser/metadata_test.go
The code to handle slices of pt hops for annotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/236)
> Sandbox batch request pt hops

- metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/239)
> Add embargo metrics

- metrics/metrics.go
Move the metrics to embargo repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/240)
> remove embargo metrics

- parser/ndt_meta.go
- parser/pt.go
- parser/ss.go
- parser/ss_test.go
- parser/util.go
- parser/util_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/242)
> add IP validation util for parsers

- .travis.yml
This may cause problems, since goveralls will execute all tests, whereas before we were only testing in 4 directories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/244)
> Add goveralls to .travis.yml

- .travis.yml
- cmd/etl_worker/app-traceroute-prod.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/245)
> let PT running in prod

- functions/README.md
- functions/embargo/README.md
- parser/ss.go
- parser/util.go
- schema/ss.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/247)
> Readme update and fix schema error

- .travis.yml
- cmd/etl_worker/app-sidestream-prod.yaml
- etl/globals.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/249)
> Move sidestream to prod

- parser/ss.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/251)
> Add err message into the log.

- bq/insert.go
- parser/disco_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/253)
> removed dead code

- cmd/etl_worker/app-ndt.yaml
- parser/metadata.go
- parser/metadata_test.go
- parser/ndt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/252)
> Last of Joseph's changes, adding flag protection.

- cmd/etl_worker/app-traceroute.yaml
- metrics/metrics.go
- parser/geo_annotation.go
- parser/ndt.go
- parser/pt.go
- parser/pt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/259)
> enable geolocation annotation on PT.

- cmd/etl_worker/app-sidestream-prod.yaml
- cmd/etl_worker/app-sidestream-staging.yaml
- cmd/etl_worker/app-sidestream.yaml
- parser/ss.go
- parser/ss_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/268)
> Enable Geo with Sidestream

- cmd/etl_worker/app-sidestream-prod.yaml
- cmd/etl_worker/app-sidestream-staging.yaml
- cmd/etl_worker/app-sidestream.yaml
- cmd/etl_worker/app-traceroute-prod.yaml
- cmd/etl_worker/app-traceroute-staging.yaml
- cmd/etl_worker/app-traceroute.yaml
So instance won't get killed when annotator stop working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/270)
> update CPU utilization target.

- cmd/etl_worker/app-ndt-prod.yaml
- cmd/etl_worker/app-ndt-staging.yaml
- cmd/etl_worker/app-ndt.yaml
This is intended to reduce the frequency of instances being removed when task is in progress.  Not sure it will work, but should not have any adverse effects aside from tiny increase in billing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/271)
> Long cool down

- cmd/etl_worker/etl_worker.go
Intended as pure refactoring, no functional change, though some things done in slightly different order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/283)
> refactor worker for reuse with pubsub

- etl/etl_test.go
- etl/globals.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/289)
> Fix validation

- bq/insert.go
- cmd/etl_worker/app-ndt.yaml
Test smaller NUM_WORKERS in sandbox.
Remove bad log msg that is spamming logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/291)
> Tweak num workers and remove bad log msg.

- .travis.yml
- appengine/queue_pusher/queue_pusher.go
- appengine/queue_pusher/queue_pusher_test.go
Add a queue parameter to the queue pusher, to support batch queues.
Also adds some basic unit tests for the receiver function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/295)
> Queue pusher

- appengine/queue.yaml
Can't use _ in queue names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/297)
> fix bad queue names

- schema/views/public_views.sh
Thought I had fixed this but it slipped through.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/368)
> Remove stray }.  Grrr

- cmd/etl_worker/etl_worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/381)
> default handler returns env vars and worker count

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/383)
> Travis deployment for views

- parser/parser.go
- parser/parser_test.go
- parser/ss_test.go
parser.go contains some test only code.  This moves it where it belongs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/382)
> Move some code to _test

- etl/etl_test.go
- etl/globals.go
- metrics/metrics.go
- parser/pt.go
- parser/pt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/385)
> Add more pt metrics

- .travis.yml
- dedup/README.md
- dedup/dedup.go
- dedup/dedup_integration_test.go
- dedup/dedup_test.go
- etl/globals.go
Some utility functions for dealing with Table objects, and listing, and getting basic and detailed info about Tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/392)
> Dedup step 1

- .travis.yml
- schema/views_legacysql/make_views.sh
- schema/views_standardsql/make_views.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/396)
> Allow multiple aliases

- .travis.yml
Clean up the block of go test, using for loops.  Should be less error prone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/400)
> Pretty coverage

- .travis.yml
This will aid testing of changes to the batch processing system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/401)
> Add batch pipeline to sandbox and staging

- bq/insert.go
- etl/globals.go
Add NewBQInserter check whether service is batch.  If it is then force all inserts to go to template table instead of partition, since target won't be the public table and we don't care about latency.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/399)
> Batch inserter

- .travis.yml
- cmd/etl_worker/app-ndt-batch.yaml
Second try.  Apparently screwed up merge on previous attempt.
This also updates travis tools to include INJECTED_PROJECT support, and uses that to adjust the project for each pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/402)
> Add ndt-batch pipeline to staging and sandbox

- metrics/metrics.go
- parser/pt.go
Updated Grafana at:
http://status.mlab-staging.measurementlab.net:3000/dashboard/db/pt-pipeline?orgId=1&from=now-30m&to=now
Too new graphs:
Polluted Tests Count Per site
Polluted Tests Percentage Per site
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/405)
> add metrics for pollution.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/408)
> Add Go Reportcard badge

- dedup/dedup.go
- dedup/dedup_integration_test.go
- dedup/dedup_test.go
This adds:
checkDetails()
checkDestOlder()
WaitForJob()
SafeCopyPartition()
CheckAndDedup()
ProcessTablesMatching()
These collectively provide all the tools we need to run dedupping jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/394)
> Dedup step 2 - more complex functions.

- .travis.yml
- schema/views_legacysql/common_etl.sql
- schema/views_legacysql/make_views.sh
- schema/views_standardsql/common_etl.sql
- schema/views_standardsql/make_views.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/409)
> Update views to use base_tables as base.

- .travis.yml
Thought I did this already but there it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/410)
> remove pushd

- .travis.yml
- parser/pt.go
- parser/pt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/413)
> Fix the panic bug introduced by pollution fix.

- .travis.yml
- batch/batch.go
- cmd/gardener/app.yaml
- cmd/gardener/gardener.go
This introduces the skeleton for the gardener service, and travis deployment rules for the sandbox and staging instances.
Next steps will introduce tasks that run periodically to find the oldest partitions in the target table, and to find candidates for deduplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/425)
> Gardener initial service definition

- cmd/gardener/app.yaml
Stupid mistake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/437)
> Fix bad comment type in app.yaml

- batch/batch.go
- batch/batch_integration_test.go
Add GetTaskqueueStats method to Queuer.
This will be used for throttling addition of new tasks to the queues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/440)
> GetTaskqueueStats

- .travis.yml
1. Make the various deployments more consistent.
a.  Sandbox all individual, and based on branch *-sandbox-* or sandbox-*
b.  Staging ONLY when merged with integration.
2.  Add big comment about deployment triggers.
3.  Add staging deployment for views.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/439)
> Clean up travis deployments

- cmd/gardener/app.yaml
- cmd/gardener/gardener.go
- cmd/gardener/gardener_integration_test.go
- cmd/gardener/gardener_test.go
Add datatstore code for persisting some batch processing state.
This also adds some structs and comments that outline how this will be used, and code that tickles it in the 5 minute periodic loop.
Also does some code organization, and tweaks the healthcheck related code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/442)
> Gardener 1

- .travis.yml
This PR corrects the injected project used by DISCO in production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/447)
> Fix: Update disco INJECTED_PROJECT to measurement-lab

- cmd/gardener/gardener.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/449)
> fix gardener date bug

- .travis.yml
Fix several problems with .travis.yml
1.  For loop was losing intermediate exit codes
2.  storage tests don't have credentials, and should not be running (for now)
3.  appengine should specify appengine/queue_pusher.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/454)
> Fix for loop

- annotation/geo.go
- parser/geo_annotation.go
This fixes triple colon bug in requests to annotator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/477)
> use  NormalizeIpv6

- parser/geo_annotation.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/479)
> Use NormalizeIPv6 for PT

- schema/views_legacysql/common_etl.sql
- schema/views_legacysql/make_views.sh
- schema/views_legacysql/ndt_plx.sql
- schema/views_standardsql/common_etl.sql
- schema/views_standardsql/make_views.sh
- schema/views_standardsql/ndt_plx.sql
Looks like _PARTITIONDATE is harder to understand and incompatible.   So continue using DATE(_PARTITIONTIME)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/483)
> Use DATE(_PARTITIONTIME)

- .travis.yml
Add deployments for queue.yaml.  Somehow these have been missing all this time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/490)
> Queue deploy

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/493)
> add TRAVIS_BUILD_DIR to appengine/queue.yaml

- annotation/geo.go
- annotation/geo_test.go
- bq/insert.go
- cmd/task_client/task_client.go
- etl/etl.go
- fake/uploader.go
- go-pre-commit
- parser/geo_annotation.go
- parser/geo_annotation_test.go
- parser/ndt.go
- parser/pt.go
- parser/ss.go
- schema/pt_schema.go
- schema/ss_schema.go
- schema/switch_schema.go
- storage/storage.go
- task/task.go
Roll forward PR that fixed many lint and vet warnings, but broke json annotations.  Patch the json annotations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/501)
> Sandbox lint vet

- functions/embargo/transfer.js
The destination buckets are implied by project name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/503)
> remove bucket name for embargo triggering

- functions/README.md
- functions/embargo/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/504)
> Update cmd for embargo cloud functions

- etl/etl.go
- parser/ss.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/524)
> clean up ss.go lint and vet

- .travis.yml
- functions/README.md
- functions/embargo/transfer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/526)
> Add cloud function to travis yml

- parser/disco_test.go
- parser/ss.go
- parser/ss_test.go
- schema/ss_schema.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/529)
> add parse_time, task_filename

- functions/enqueue.js
- functions/enqueue_test.js
This change updates the queueForFile logic to return the correct task queue for the disco parser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/533)
> Correct enqueue queueForFile logic for switch data

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/535)
> Add cloud function deploy for parser task queue triggering in .travis.yml

- cmd/etl_worker/app-sidestream.yaml
Sidestream pipeline instance parameters have fallen out of date.  This PR adjusts them to be more consistent with other updates and observed behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/539)
> Adjust out of date yaml parameters

- .travis.yml
- appengine/queue.yaml
- cmd/etl_worker/fast-sidestream.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/549)
> travis, queue, and appengine changes for fast-ss demo

- appengine/queue.yaml
This change adds the disco & traceroute task queues to queues.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/561)
> Add traceroute and disco batch queues to queues.yaml

- etl/globals.go
- etl/globals_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/573)
> Add translation func from gs dir to BQ table name

- cmd/etl_worker/app-batch.yaml
We want to allow a large number of instances to get quickly through our backlog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/576)
> allow up to 250 instances for rapid reprocessing

- appengine/queue.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/577)
> Increase max concurrent by 5x for rapid reproc

- annotation/geo.go
- cmd/etl_worker/app-batch.yaml
- cmd/etl_worker/app-disco.yaml
- cmd/etl_worker/app-ndt.yaml
- cmd/etl_worker/app-sidestream.yaml
- cmd/etl_worker/app-traceroute.yaml
Missed this on last PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/597)
> Remove ANNOTATE_IP environment var

- annotation/export_test.go
- annotation/geo.go
- annotation/geo_test.go
- parser/geo_annotation_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/599)
> Use the new annotator-service/api.GetAnnotations

- annotation/geo.go
- metrics/metrics.go
Missed a return.  Argh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/601)
> return on annotation error

- cmd/etl_worker/etl_worker.go
- metrics/metrics.go
- metrics/metrics_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/621)
> Clean things up to use promauto and prometheusx

- .travis.yml
The etl-schema change adds the "radius" field to ndt and sidestream tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/623)
> Update etl-schema submodule

- cmd/etl_worker/etl_worker.go
Adds the task age to the "Received" log message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/632)
> Add task age

- annotation/geo_test.go
- metrics/metrics_test.go
- parser/geo_annotation_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/635)
> Fix broken unittests due to package moved and outside proto change

- cmd/etl_worker/etl_worker.go
Somehow a bad version of eta parsing made it into master.  This fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/636)
> fix eta parsing

- .travis.yml
In service of https://github.com/m-lab/dev-tracker/issues/224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/637)
> Adds metric that record the commit hash.

- annotation/geo.go
- annotation/geo_test.go
- parser/geo_annotation.go
- parser/geo_annotation_test.go
- parser/ndt.go
- parser/ss.go
- schema/web100.go
This plumbs through the ASN annotations from the batch response to the NDT rows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/639)
> NDT asn annotation plumbing

- .travis.yml
use go 1.12 for logging dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/648)
> Batch sandbox go112

- annotation/geo.go
- metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/649)
> add metrics for annotation missing fields

- annotation/geo.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/650)
> fix panic caused by recent metrics code

- etl/globals.go
- parser/disco_test.go
- parser/geo_annotation.go
- parser/geo_annotation_test.go
Introduce data type for tcpinfo.
Also fixes some go vet warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/652)
> Add tcpinfo type.

- parser/base.go
- parser/base_test.go
- parser/tcpinfo.go
This adds the Annotatable interface, and a parser Base that handles buffering, annotation, and flushing to inserter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/654)
> Parser base

- parser/base.go
- parser/parser.go
- parser/ss.go
- parser/ss_test.go
- schema/schema_test.go
- schema/ss_schema.go
1. Rename BaseRowBuffer to just RowBuffer
2. Make SS struct implement Annotatable.
3. Add additional error checking in Base.
4. Embed new Base in SSParser.
5. Add annotation to unit test.
6. Remove RowBuffer from ss.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/659)
> Use parser/base to simplify sidestream parser.

- parser/geo_annotation.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/660)
> Fix annotation request error for NDT

- parser/ss.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/664)
> fix ss pointer error

- parser/base.go
- parser/ndt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/668)
> add metrics for RPC failures

- schema/web100.go
Removes a noisy log.Println from web100 map navigation code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/672)
> reduce log spam

- appengine/queue.yaml
I'll think about a better way to do this, but this will help for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/687)
> Make tcpinfo task queue slower, so processing doesn't wrap too quickly.

- appengine/queue.yaml
- bq/insert.go
- etl/globals.go
- etl/globals_test.go
- schema/pt_schema.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/694)
> Batch sandbox pt

- appengine/queue.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/700)
> Increase processing rate for ndt legacy queue

- cmd/update-schema/update.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/710)
> Add schema tool for new traceroute schema

- appengine/queue.yaml
fix tons of rate limit exceed error in sandbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/709)
> traceroute perf tuning

- bq/insert.go
- parser/ndt.go
- parser/ndt_meta.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/725)
> reduce log spam from hot logs, tweak others

- parser/pt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/740)
> dup of #739

- functions/enqueue.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/744)
> Feed traceroute from other tests to ETL processing

- .travis.yml
As a temporary solution to https://github.com/m-lab/etl/issues/751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/754)
> Comment out queue pusher from .travis.yml

- parser/pt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/764)
> error message fix

- etl/globals.go
For https://github.com/m-lab/etl-gardener/issues/204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/765)
> pt tuning to increase parsing coverage

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/766)
> Remove Waffle, as Waffle.io is no more

- parser/pt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/776)
> Add loginfo for traceroute failed json parsing

- .travis.yml
There is a problem deploying universal to staging, so this disabled that deployment until we can fix the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/777)
> remove universal from staging deployment

- .travis.yml
This restores the universal staging deployment.  Previously was using the wrong service account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/778)
> fix staging universal

- active/active.go
- active/active_test.go
- active/runnable.go
- active/throttle.go
- active/throttle_test.go
- metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/779)
> Add a throttling wrapper for job Source

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/787)
> remove broken staging universal deployment

- schema/schema.go
To facilitate faster development of new documentation, this change adds a flag that allows a user to specify an external source for the schema descriptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/789)
> Add flag to allow runtime override of the schema asset location

- active/active.go
- cloud/gcs/gcs.go
Add the correct imports, for compatibility with module changes in m-lab/go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/797)
> fix googleapi imports

- .travis.yml
- parser/pt.go
- parser/pt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/796)
> handle panic caused by unknown PT format.

- .travis.yml
- active/active.go
- active/active_test.go
- active/runnable.go
- active/throttle.go
- active/throttle_test.go
- cmd/etl_worker/Dockerfile.k8s
- cmd/etl_worker/etl_worker.go
- etl/globals.go
- k8s/data-processing/deployments/parser.yml
1. Minor improvements to active code.
2. Dockerfile.k8s static linking, on alpine, avoiding net segfault issue.
3. Small config and buffer size tweaks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/800)
> Improve active

- active/active.go
- active/active_test.go
- active/poller.go
- active/poller_test.go
- active/throttle_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/801)
> Add GardenerAPI with code to poll for jobs and send updates.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/807)
> fix docker build for app engine?

- active/throttle_test.go
- cmd/etl_worker/etl_worker.go
- metrics/metrics.go
This enables active job parsing when GARDENER_HOST is specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/808)
> Activate job polling and dispatch when GARDENER_HOST is specified.

- parser/pt.go
- parser/pt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/810)
> Fix code path that generate empty row

- parser/pt.go
- parser/pt_test.go
- schema/tcpinfo.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/811)
> Add new field for test FileName for traceroute

- cmd/generate_schema_docs/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/816)
> Generate rich md text when Discussion & Kernel keys are found

- parser/tcpinfo.go
- parser/tcpinfo_test.go
See #831
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/832)
> keep only 1/10 of snapshots

- parser/tcpinfo.go
Adds TestCount stats to TCPInfoParser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/837)
> Add TestCount stats

- row/row.go
- storage/rowwriter.go
- storage/rowwriter_test.go
- storage/storage.go
This implements Sink api with a GCS backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/840)
> Add GCS backed rowwriter

- active/poller.go
This temporarily uses a local job.NextJob to isolate from changes about to be made to etl-gardener in m-lab/etl-gardener/#233.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/841)
> use local job.NextJob for transition

- bq/insert.go
This improves the logs and metrics.
Some of the ErrorCount metrics were incorrect.  Some error counts will be large with the corrected code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/843)
> better insert error log

- bq/insert.go
- row/row.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/844)
> Fix goroutine "leak" introduced last week in tcpinfo

- cmd/etl_worker/etl_worker.go
- etl/etl.go
- etl/globals.go
- etl/globals_test.go
- storage/storage.go
- storage/storage_test.go
- worker/worker.go
Fixes small (non-functional) errors and omissions in previous refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/847)
> Tweak previous refactoring.

- row/row.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/851)
> delete spammy debug logs

- cmd/etl_worker/etl_worker.go
- parser/annotation.go
- parser/ndt5_result.go
- parser/ndt7_result.go
- parser/tcpinfo.go
This fixes a nil injection bug, cleans up some parser code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/864)
> Fix bad injection

- metrics/metrics.go
- parser/tcpinfo.go
- worker/worker.go
This fixes some bugs in metric labels and adds gauges for the git commit and release strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/878)
> Fix labels, add commit and release tags

- active/poller.go
- etl/globals.go
- etl/globals_test.go
- parser/annotation.go
- parser/ndt.go
- parser/ndt5_result.go
- parser/ndt7_result.go
- parser/tcpinfo.go
- row/row.go
- storage/rowwriter.go
- task/task.go
Adds some missing metrics
Adds PathAndFilename func
Some log cleanup and misc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/901)
> Metrics and misc

- storage/export_test.go
- storage/rowwriter.go
- storage/rowwriter_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/910)
> Add pathAndFilename, and NewSinkFactory

- cmd/etl_worker/etl_worker.go
- cmd/etl_worker/etl_worker_test.go
- k8s/data-processing/deployments/parser.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/921)
> Refactor main, add unit test

- parser/disco.go
- parser/disco_test.go
When parsing DISCO data, the parser used to drop the final, overlapping sample from each file to avoid duplication. However, there is no overlapping or duplication in the output of DISCOv2, so in that case we want the entire sample. This PR looks for files ending with `jsonl` (the outpuf of DISCOv2) and if it find it, it will use the entire sample, else it will eliminate the final sample (data coming from collected in the utilization experiment).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/924)
> Uses whole sample for DISCOv2.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/930)
> Add prod deployment rule

- .travis.yml
- cmd/update-schema/update.go
This adds update-schema enhancements for ndt7 and annotation, and incorporates the correct commands into the travis deployments.
It also update etl-schema subproject to the latest version, and updates the production batch trigger to include the universal parser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/932)
> add ndt7 and annotation update-schema

- cmd/etl_worker/app-batch.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/939)
> add prometheus port

- active/active_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/960)
> fix bug after go package update

- cmd/etl_worker/app-batch.yaml
- k8s/data-processing/deployments/parser.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/959)
> reduce to 40 instances to reduce legacy cost

- cmd/etl_worker/app-batch.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/962)
> reduce to 4-6 instances, smaller memory

- cmd/etl_worker/app-batch.yaml
This change increases the resources assigned to the legacy batch parser. This change will allow faster reprocessing of historical data types in preparation for the annotation export process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1010)
> Increase legacy batch processing

- Dockerfile.testing
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1016)
> Add --allow-releaseinfo-change flag to update step in Dockerfile.testing

- parser/scamper1.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1072)
> Log ArchiveURL in scamper1 errors

- cloudbuild.yaml
Runs update-schema for msak's annotation2 datatype.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1120)
> Run update-schema for msak's annotation2 datatype

- cloudbuild.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1123)
> Generate pcap datatype schema for msak experiment

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1130)
> Update coveralls config for etl
