.personalize_deploy.sh, .travis.yml
This change adds personalized service names for deployments from sandbox-<username>.
The "etl-parser" service is decorated with the username as "etl-parser-<username". This will allow parallel experimentation with the appengine flexible environment service.
As well, the "integration" branch is recognized for deployment as well, but this will not decorate the service name. As a result, the integration branch can be our canonical reliable service between reviews.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/6)
=> Add support for personalized service deployments

parser/parser.go, parser/parser_test.go
This introduces the Parser interface, and a NullParser implementation.  Real and Pseudo parser implementations should be based on this code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/8)
=> Parser interface and NullParser

cmd/etl_worker/etl_worker.go, metrics/metrics.go
This change adds a new package for defining prometheus metrics used throughout the etl pipeline.
As well this change imports the `/net/http/pprof` package to enable real time profiling information from deployed services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/9)
=> Add prometheus metrics and pprof support to etl_worker 

appengine/push_queue/README.md, appengine/push_queue/app.yaml, appengine/push_queue/push_queue.go, cmd/etl_worker/etl_worker.go, functions/enqueue.js
This change adds a microservice to run in AppEngine Standard Environment that accepts requests and creates a Task to add to a Push queue using the given parameters.
The push-queue service is necessary because the Push taskqueue API is only supported (apparently) by AppEngine SE packages. The public REST API does not appear to support push queues.
This change also adds psuedo-processing in the `etl_worker` push queue target.
This change updates the cloud function to issue a request to the new push-queue receiver. This change is not yet deployed.
TODOs:
* automate deployment of the push-queue SE app.
* automate deployment of the cloud functions.
* identify the correct way to load prometheus metrics per- flex instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Add push-queue AppEngine SE service

cmd/etl_worker/etl_worker.go, storage/storage.go, storage/storage_test.go, task/task.go, task/task_test.go
Some general cleanup.
Move NextTest to storage.
Rename TarReaderCloser to ETLSource.
Simplify Closer handling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/24)
=> Move NextTest to storage package.  Improve names

.travis.yml, bq/bq_test.go, bq/insert.go, cmd/etl_worker/etl_worker.go, fake/atomiccache.go, fake/fields.go, fake/fold.go, fake/uploader.go, intf/intf.go, parser/parser.go, parser/parser_test.go, task/task.go, web100/web100.c
Steals a small bit of bigquery code, so that we can create a fake Uploader for testing and debugging.
Introduces FakeUploader and NewFakeInserter.
Uses the new fake in a unit test.
Changes llu to lu in web100.c to silence stupid warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/29)
=> Fake Uploader

cmd/etl_worker/etl_worker.go
This change adds a new listening port on port 9090 for the prometheus metrics exporter for the etl-parser service.
We need a separate service since AppEngine does not support forwarding the port used for the main service (8080 by default). The change needed to app.yaml is already in place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/35)
=> Add separate listening port for prometheus metrics.

cmd/etl_worker/etl_worker.go
This change adds pprof handlers to the exporter port.
The handlers still exist on the default port, however due to App Engine it is not predictable which backend instance we contact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/37)
=> Add explicit pprof handlers to the exporter port.

.travis.yml, bq/insert.go, storage/storage.go, task/task.go, web100/web100.c, web100/web100.go
This change includes increases to timeouts for BQ inserts, and GCS downloads.
As well, this change includes three fixes to web100.c observed to cause runtime failures with historical ndt snaplog files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/47)
=> Fixes to timeouts, busy-loops, stack-smash SIGSEGV

parser/ndt.go, web100/web100.go
This change shortens the time that `web100.Open` holds the web100Lock.
The lock was held until close because we were seeing some very large snaplog files in production.
However, now that we are filtering unusually large files there is almost no risk of filling the tmpfs directory as long as we continue to limit the number of simultaneous tasks and average snaplog size to fit in the tmpfs directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/53)
=> Shorten time that web100Lock is held.

web100/web100.c, web100/web100.go
This change addresses some additional functional bugs that caused process termination like issues: #57 #56 #55 .
Changes include:
* calloc instead of malloc throughout web100.c
* additional checks for NULL return values within web100.c, where errors are possible but previously unhandled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/58)
=> Return the big-web100-lock and add preventative checks for NULL

cmd/web100_cli/web100_cli.go, etl/globals.go, parser/ndt.go, parser/ndt_test.go, schema/web100.go, web100/web100.go
This change adds support for a schema that more closely matches the current production web100 schema for NDT.
TODO:
* Update the table name for testing.
* implement the fixValues function to support IPv6 and other record fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/61)
=> Add NDT support for full schema

parser/ndt.go, parser/ndt_test.go
This does some straightforward refactoring (without much cleanup) in preparation for handling .meta files.
Also adds a regex parser for the test file names, which will aid in the meta file handling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/71)
=> refactoring and regexp parsing

parser/ndt.go, storage/storage.go, task/task.go
Some small cleanups:
Add proper handling of .gz files (since Peter's scraper change)
Handle errors locally instead of returning to caller.
Modify backoff times for retries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/75)
=> Small tweaks

bq/bq_test.go, bq/insert.go, cmd/etl_worker/etl_worker.go, etl/etl.go, etl/globals.go, metrics/metrics.go, parser/disco.go, parser/disco_test.go, parser/ndt.go, parser/ndt_test.go, parser/parser.go, parser/pt.go, task/task.go
Add handling of bigquery partitions.
BQ allows streaming into partitions up to 30 days in the past, and 7 days into the future.  Outside that range, we use template table creation to write into a separate table with an _YYYYMMDD suffix.
Also updates the metrics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/76)
=> Use date partitions

bq/bq_test.go, bq/insert.go, cmd/etl_worker/etl_worker.go, etl/etl.go, metrics/metrics.go, parser/disco.go, parser/disco_test.go, parser/ndt.go, parser/ndt_test.go, parser/parser.go, parser/pt.go, storage/storage.go, task/task.go, task/task_test.go
Currently, task embeds both Parser and Inserter.  This exposes more of the Inserter interface than is perhaps healthy.
To improve handling of .meta file data in NDT tests, I want to have Parser also implement Flush.  With both Parser and Inserter embedded, this would confuse the interfaces.
This PR:
1. Modifies the stats reported by Inserter, and bundles them into new RowStats interface.
2. removes embedded Inserter from Task
3. exposes the RowStats, Flush, and FullTableName through Parser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/124)
=> refactor task and parser

parser/ndt.go, parser/ndt_meta_test.go, parser/ndt_test.go
Previously, c2s and s2c tests were processed and forwarded to the inserter as soon as a meta file was available.  If a new test came in before .meta file, the tests were processed without the meta file.
This lead to orphaned tests if the tests at the end of a tar file had no meta file.
This restructures the handling of test groups, and allows explicitly processing the last group at the end of the tar file, in the Flush() function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/127)
=> new group deferal strategy and collision handling

appengine/queue.yaml, bq/insert.go, cmd/etl_worker/app-ndt.yaml, cmd/etl_worker/etl_worker.go, cmd/web100_cli/web100_cli.go, etl/globals.go, metrics/metrics.go, parser/ndt.go, schema/README.md, schema/ndt.json, schema/web100.go, web100/web100.go, web100/web100_test.go
Adds "delta" snapshots to the schema.  Only fields that change are reported, and all other fields are null, indicating that their value is same as previous delta.
Adds web100.SnapshotDeltas, which records delta snapshot into a Saver.
Adds delta handling in NDT parser, along with useful metrics.
Updates etl_worker, queues, etc., to maintain appropriate pacing and scaling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/128)
=> Add Snapshot Deltas

.personalize_deploy.sh, .travis.yml
Looks like .personalize_deploy.sh has a bug that we haven't noticed, because we disabled the base deployment some time ago.
I think I got this right, but can't test, so please read carefully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/132)
=> fix personalize_deploy to work with arbitrary yaml

.travis.yml
Clean up handling of different targets in sandbox deployments.
Add standard standbox deployment for NDT only on integration branch.
Add staging branch deployment for NDT only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/133)
=> separate sandbox targets, add ndt-staging

parser/ndt.go
Refine the metrics and logging for combinations of meta/s2c/c2s.  This will help understand the failure in NDT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/141)
=> report all combinations of meta/s2c/c2s

appengine/queue.yaml
Also adjust storage limit, since scraper now produces many more files.  Not clear if this is needed, but no harm if it isn't, and it appears that tasks are lost if the task queue is filled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/142)
=> adjust queue params to avoid rate quota

cmd/etl_worker/etl_worker.go, etl/globals.go, metrics/metrics.go, task/task.go, task/task_test.go
This PR adds minimal support for reconciling the number of files uploaded per day by scraper with the number of files processed per day by the etl workers. This PR is a companion to https://github.com/m-lab/scraper/pull/72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/148)
=> Count the files collected daily per host and rsync module

bq/insert.go, cmd/etl_worker/app-ndt-prod.yaml, cmd/etl_worker/etl_worker.go
Use environment variables to specify the destination table project/dataset.  This allows the same binary to be configured for sandbox, staging, or prod.  Production pipeline runs in mlab-oti, but writes to tables in measurement-lab, so we can't just use GCLOUD_PROJECT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/152)
=> Prod config

appengine/queue_pusher/queue_pusher.go, functions/README.md, functions/embargo/transfer.js, functions/enqueue.js
projectId is unreliable, so don't use it.
project is hard coded into enqueue functions, so clone them for different projects.
fix a bug in queue_pusher to prevent panics.
fix some jslint complaints.
adjust readme doc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/165)
=> Clean up gcf functions for initial prod deployment.

cmd/etl_worker/app-ndt-prod.yaml, cmd/etl_worker/app-ndt.yaml, cmd/etl_worker/etl_worker.go, parser/ndt.go
This adds a yaml configured environment variable to specify the max number of workers (MAX_CONCURRENT_REQUESTS), and code in etl_worker.go to use it.
This allows tuning of each individual pipeline for best performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/167)
=> Add MAX_CONCURRENT_REQUESTS environment variable

etl/globals.go, parser/ndt.go
This change addresses the problem of "when no_meta, the `server_hostname` is missing entirely" from https://github.com/m-lab/etl/issues/168
The `server_hostname` is reconstructed from the archive filename. This requires hard-coding the `measurement-lab.org` domain suffix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/170)
=> Fix NDT server_hostname when missing from connSpec

parser/ndt_meta.go, parser/ndt_meta_test.go, parser/testdata/20170509T13:45:13.590210000Z_eb.measurementlab.net:53000.meta, schema/ndt.json, schema/web100.go, web100/web100.go
This PR addresses two issues:
* client_kernel_version & client_version are parsed from .meta files addressing this issue from https://github.com/m-lab/etl/issues/168
* "tls" and "websocket" are added as new columns with unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/172)
=> Add missing NDT client values & Add tls & websocket columns

parser/ndt.go, parser/ndt_test.go
Since the connSpec is a `map[string]bigquery.Value` the empty value is `nil` if `server_hostname` is not present. So this change explicitly checks whether `server_hostname` is present and if it is that it is not empty. If it is missing or empty, the value is constructed and set.
Addresses issue from: https://github.com/m-lab/etl/issues/168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/185)
=> Fix check for server_hostname

.personalize_deploy.sh
On line 26, it wasn't supposed to double quote args 3 & 4 together. They're supposed to be separate arguments to the script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/197)
=> Fix bug with personalize deploy

appengine/queue.yaml
Since the pipeline is now running concurrently with the scraper, it should be fine to allow it to run more slowly, keeping resource to a minimum.  At this rate, the ingestion takes about 6 hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/166)
=> tweak queue rate

appengine/README.md, appengine/sandbox-queue.yaml
Adjusting ndt queue rate so that there is a trickle all day.  This will facilitate annotation service development.
Also adjusting PT queue rate to avoid bigquery insert quota problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/194)
=> Reduce ndt and pt rate, and remove obsolete queue

storage/storage.go, task/task.go, task/task_test.go
We occasionally see a 2 GB single test file.  This causes OOM, which causes reprocessing of any tasks partially completed by other workers.
Also, since the task was not successful, the task queue keeps resubmitting it, causing additional OOMs.
This PR restricts the max single test size to 200MB, (200 times the nominal test size).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/195)
=> Add max file size, and clean up error handling

annotation/geo_structs.go, geo/annotation_structs.go, parser/metadata.go, parser/metadata_test.go, schema/pt_schema.go, schema/ss_schema.go
The geo code is currently spread across the schema and parser directories, and each file mixes content that should be at different dependency levels.  This is currently avoid circular dependencies, but not in a clean way.
So, I am moving the geo specific code into a new package, eliminating the structs from the schema package.
Step 1...
Moves the "schema" file to annotation/geo_structs.go and renames.
Fix package prefix for references to structs.
Add EnableAnnotation flags, which allows us to run this in sandbox but not propagate to prod
until we are ready.
Step 2...
Cut and paste geo specific code from parser package into annotator/geo.go and _test files.
Fix package prefixes.
Step 3...
Merge the geo_structs.go into geo.go.  (This is combined into a PR that also adds the 1 second timeout …
=> Extracting geo code to separate package.

annotation/geo.go
The annotator 99th percentile response time is over 0.6 sec.  This results in about 0.05% of annotations failing.  Increasing timeout to 2 seconds should reduce the failures to a very small level.
We need to watch to ensure that this does not reduce cpu utilization too low when the annotator is offline.  I will test on sandbox before merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/267)
=> Increase timeout to 2 seconds

.travis.yml, README.md, appengine/queue.yaml, cmd/etl_worker/app-ndt-batch.yaml, cmd/etl_worker/app-ndt-prod.yaml, cmd/etl_worker/app-ndt-staging.yaml
This adds another production NDT config, with up to 50 instances, for large batch processing jobs.
NB: the && in the script.  Not sure if this is best way to do this.  Perhaps should have separate scripts, but triggered by the same tag??
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/272)
=> Add batch processing service

bq/insert.go, etl/etl.go, parser/disco.go, parser/ndt.go, parser/ndt_test.go, parser/parser.go, parser/pt.go, parser/ss.go, task/task.go, task/task_test.go
Issue #262
There are two cases where we see high row insert errors, but files are not reprocessed.
1.  table is missing and all inserts fail.
2.  insert quota is exceeded, and many inserts fail.
Adds a parser.TaskError check at end of task processing.  
Adds NDT TaskError implementation that fails if more than 10% of row adds failed.
This may result in more dups, if there are spurious errors in excess of 10%, e.g. when there are lots of quota errors.
This enables, but does not address, handling of similar problems in other parsers.  Will add issues to address those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/274)
=> Fail tasks with high row errors

bq/bq_test.go, bq/insert.go, etl/etl.go, fake/uploader.go, parser/disco_test.go
If we are pushing too much data to bigquery, we get Quota exceeded errors.
This adds code to retry up to 10 times, with a sleep() between calls.  The sleep is currently configured for 30 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/276)
=> Retry on quota exceeded error

.travis.yml
This change adds support for deploying the queue-pusher service for staging and production based on tags. The tagging patterns follow the same convention as other examples already present in the .travis.yml file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/288)
=> Add deployment directives for staging and prod

appengine/queue.yaml
This will be used primarily in production, to feed the etl-ndt-batch-parser.  Currently other appengine configs do not configure a batch pipeline.
Also removes the unused pull queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/292)
=> Multiple batch queues

cmd/etl_worker/app-ndt.yaml, parser/ndt.go
For near term, we can produce tables without deltas about 5 times faster than with deltas.  We will provide some test tables with deltas, and add deltas back into the main tables in a couple months.
This does some refactoring, and adds an env var check that disables delta generation.  It also sets the env var for sandbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/302)
=> Suppress delta generation

bq/insert.go, cmd/etl_worker/app-ndt-batch.yaml, cmd/reproc/reproc_test.go, etl/globals.go
When NDT_OMIT_DELTAS is set, each row is much smaller, so we can buffer more rows.  This should improve throughput, and likely reduce the number of workers or instances needed.
I'm not entirely happy about having NDT details in globals.go, but it seems much better than having them in insert.go.   If you have a better idea please suggest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/375)
=> Adjust insert buffer size for no-deltas

.travis.yml
This adds two deployment targets - staging-* and prod-*, which deploy all etl pipelines, instead of individual pipelines.
Leaving the individual targets for now, but probably should remove them later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/380)
=> Add travis env vars to app-engine deployments.

cmd/etl_worker/app-ndt-prod.yaml
We have agreed to use dataset base_tables instead of public for the continuous pipeline output.
This also disables snapshot deltas, and adjusts worker and instance limits.
Before pushing to prod, need to suspend the task queue to avoid having to merge old and new table.
critzo - this is just an FYI - won't wait for your review, but feel free to comment.
Issue #403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/404)
=> Parse to base_tables instead of public

etl/globals.go, parser/disco.go, parser/disco_test.go, schema/README.md, schema/switch.json, schema/switch_schema.go
This change adds disco switch support to the ETL parser.
A new schema definition is included, and the output table renamed to the more recognizable name "switch".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/431)
=> Update the DISCO switch schema

metrics/metrics.go
This change restores the registration of the InsertionHistrogram metric that was accidentally removed by https://github.com/m-lab/etl/pull/415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/434)
=> Restore registration of InsertionHistorgram metric

.travis.yml, metrics/metrics.go, parser/disco.go, schema/switch_schema.go
This change uses the explicit key path for ndt-batch. Evidently the previous form resulted in a file name like `/tmp/.json`. 
This kind of bug may be an argument for a stand-along deploy script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/444)
=> Fix: Use explicit key path for ndt-batch

metrics/metrics.go, parser/disco.go, schema/switch_schema.go
This change enhances the etl metrics and adds new metrics to disco.
Specifically, the http status code text is now a label on HistogramDuration, making it possible to report QPS, successful request latency, and error rates.
As well, this change adds TODOs to generalize four metrics currently only used by NDT.
The four categories are:
* bytes / test
* rows / test
* bytes / row
* fields / row
Currently these metrics are NDT specific, so eventually their names should be changed, but not before establishing that they can be used by multiple parsers.
- FileSizeHistogram - bytes/test
- EntryFieldCountHistogram - rows/test
- RowSizeHistogram - bytes/row
- DeltaNumFieldsHistogram - fields/row
The first part of this is havign DISCO use them with smaller values added to EntryFieldCountHistogram and …
=> Add new metrics to disco parser, prepare for generic size metrics

.travis.yml
This change adds the disco parser to the "small-prod" and "prod" deployment groups.
Disco uses the same app-disco.yml for each projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/446)
=> Add production disco deploy commands

etl/etl.go, metrics/metrics.go, parser/disco.go, parser/ndt.go, parser/pt.go, parser/ss.go, task/task.go
This change adds a new method to the Parser interface that reports whether a file is parsable, along with the canonical name for the "kind" of file. With this information, the task can decide at run time whether each file IsParsable and whether to call ParseAndInsert.
As well, this change uses FileSizeHistogram for all parsers, and distinguishes them using the parser destination table name, file "kind" and whether the files are parsed or ignored.
Previously, FileSizeHistogram was only used by the NDT parser. This change provides similar information for all parsers.
For NDT there is slightly less information, because the "normal" and "huge" categories are merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add IsParsable to Parser interface & generalize FileSizeHistogram

parser/parser_test.go, task/task_test.go
This change completes changes from https://github.com/m-lab/etl/pull/448 to add a new method to the Parser interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/453)
=> Implement Parser interface for test parsers

.travis.yml, schema/views_legacysql/common_etl.sql, schema/views_legacysql/make_views.sh, schema/views_legacysql/ndt_exhaustive.sql, schema/views_standardsql/common_etl.sql, schema/views_standardsql/make_views.sh, schema/views_standardsql/ndt_exhaustive.sql
This PR generalizes the sql and make_views.sh files to support creation of views in any project.  It also adds an individual views-sandbox target to allow pre-merge testing.
In parallel, I have added an appropriate ROLE in mlab-sandbox to support the view deployment.  This should also be added in staging and prod.  Prod currently has some other permission mechanism set up.
Still TODO:
1.  The views in the legacy dataset are not yet automated.  I've added an issue #457 to track this.
2.  We may want to have separate service accounts for this, rather than broadening the set of roles allowed to the standard deployment SA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/458)
=> Views sandbox

.travis.yml, etl/globals.go, etl/globals_test.go
This change adds support for parsing embargo archive file names, which add an additional `-e` suffix to files. This change allows us to ad-hoc process embargo'd files such as sidestream for data analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/463)
=> Add support for ignoring the embargo archive suffix

parser/ss.go, parser/ss_test.go
This change adds support to the Sidestream parser for combining the StartTimeStamp and StartTimeUsec web100 values into a single int64 value.
This change reports StartTimeStamp in the same way as it is reported by the NDT parser.
Unfortunately, the sidestream and ndt parsers use incompatible datatypes for holding the web100 values (schema.Web100Snap struct or sidestream, schema.Web100ValueMap for ndt), so there is no shared code between them for handling the conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/476)
=> Combine StartTimeStamp with StartTimeUsec as int64 value

cmd/etl_worker/app-ndt-batch.yaml, etl/globals.go, storage/storage.go
These are all related to limitations discovered when reprocessing sidestream data.
extend timeout on storage object reads
increase minimum number of batch instances and decrease cpu target
increase buffer size for sidestream
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/478)
=> various parameter tweaks

appengine/queue.yaml, cmd/etl_worker/app-ndt-batch.yaml
Add more batch queues.
Add retry params for batch queues to improve behavior.  Backoff causes sidestream to pulse badly.
Increase workers to 15, which is a good compromise between SS and NDT.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/485)
=> Queue tweaks

parser/disco.go, parser/pt.go
Currently, the Sidestream and NDT parsers increment TestCount on every successful call to `InsertRow`. This change updates the paris-traceroute and disco parsers to do the same. With this change, the DailyParserVolumeTooLow alert will measure volume changes on the number of row inserts consistently across all parsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/491)
=> Increment TestCount when InsertRow is successful

annotation/geo.go, annotation/geo_test.go, bq/insert.go, cmd/task_client/task_client.go, etl/etl.go, fake/uploader.go, go-pre-commit, parser/geo_annotation.go, parser/geo_annotation_test.go, parser/ndt.go, parser/pt.go, parser/ss.go, schema/pt_schema.go, schema/ss_schema.go, schema/switch_schema.go, storage/storage.go, task/task.go
This PR cleans up a number of go vet warnings.  It also fixes all the "context" imports that used an obsolete version of context.
I suspected a possible ipv6 triple colon bug in the geo_annotation.go code related to cip and sip (client and server ip addresses).  Added a unit test to try to expose it, but it seems that it is WAI.  Left the test there anyway.
After these changes, etl passes the following vet checks.
go tool vet --shadow .
go vet ./annotation/... ./appengine/... ./fake/... ./metrics/... ./schema/... ./task/... ./web100/...
go vet -assign -atomic -bool -buildtags -cgocall -copylocks -httpresponse -methods -nilfunc -printf -rangeloops -shift -structtags -tests -unreachable -unsafeptr -unusedresult ./bq/... ./etl/... ./parser/... ./storage/...
---
This change is [<img …
=> Various go vet and go fix fixes

annotation/geo.go, annotation/geo_test.go, bq/insert.go, cmd/task_client/task_client.go, etl/etl.go, fake/uploader.go, go-pre-commit, parser/geo_annotation.go, parser/geo_annotation_test.go, parser/ndt.go, parser/pt.go, parser/ss.go, schema/pt_schema.go, schema/ss_schema.go, schema/switch_schema.go, storage/storage.go, task/task.go
Reverts m-lab/etl#498, i.e., restores (most of) 497.
#497 removed spaces from json annotations, which caused json to respect annotations it had been ignoring.  Those annotations are actually incorrect, and have to be removed when the spaces are removed. 
Original description from #497:
This PR cleans up a number of go vet warnings. It also fixes all the "context" imports that used an obsolete version of context.
I suspected a possible ipv6 triple colon bug in the geo_annotation.go code related to cip and sip (client and server ip addresses). Added a unit test to try to expose it, but it seems that it is WAI. Left the test there anyway.
After these changes, etl passes the following vet checks.
go tool vet --shadow .
go vet ./annotation/... ./appengine/... ./fake/... ./metrics/... …
=> Restore "Various go vet and go fix fixes" avoiding breakage

functions/embargo/transfer.js
Calculate the destination bucket from the name of the project, rather than referring to a now-deleted local variable, and causing a crash. Deploying to staging in advance of review.
First step in addressing https://github.com/m-lab/scraper/issues/308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/506)
=> Fix the naming of the destination bucket.

.travis.yml, functions/embargo/package.json, functions/enqueue_test.js, functions/package.json
The unit tests are now fixed. In the future, this should be caught by the fixes for https://github.com/m-lab/git-hooks/issues/10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/507)
=> We changed function names without running the unit tests.

metrics/metrics.go
This change registers the already present `FileCount` metric which counts the number of tar files processed by the ETL parsers.
With this metric it will be possible to compare the output from the etl-embargo to the input of the etl parsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/510)
=> Register the FileCount metric for counting tar files

bq/insert.go, cmd/etl_worker/etl_worker.go, etl/globals.go, etl/globals_test.go
This introduces a bit of code to determine which dataset to use, based on very simple logic.
1. Sidestream:  use "private", because it includes embargoed data
2. Batch: use "batch"
3. Otherwise: use "base_tables" (for the daily pipeline)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/513)
=> choose dataset based on datatype and batch

appengine/queue.yaml
Looks like our traffic has grown such that the task queue rate no longer has any headroom for NDT pipeline task queue.
Doubling the rate to provide more headroom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/517)
=> increase ndt queue rate to provide headroom

.travis.yml, bq/bq_test.go, bq/insert.go, cmd/etl_worker/app-disco.yaml, cmd/etl_worker/app-ndt-batch.yaml, cmd/etl_worker/app-ndt-prod.yaml, cmd/etl_worker/app-ndt-staging.yaml, cmd/etl_worker/app-ndt.yaml, cmd/etl_worker/app-sidestream.yaml, cmd/etl_worker/app-traceroute.yaml, cmd/etl_worker/etl_worker.go, etl/etl.go, etl/globals.go, etl/globals_test.go, parser/disco_test.go, parser/ndt_test.go
This PR:
1. adds a Project parameter to InserterParams,
2. regularizes selection of project, dataset, and table in etl/globals.go.
3. eliminates export of previously exported maps in globals.go, (replacing with methods)
4. switches from singleton BQ client to client per task, to allow sidestream tasks to use a different client associated with possibly different project.
Also implements TODO to cleanup obsolete dataset parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/518)
=> Compute project and dataset

annotation/geo.go, bq/insert.go, etl/etl.go, storage/storage.go
1. Fix the defered cancel.
2.  Add a missing cancel.
3. Replace annotation error logging with metric.
4. Improve the backoff strategy for failed bq inserts.
5. Increase weird storage timeout to 5 hours.  We are seeing SS timeouts with 1 hour context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/522)
=> Ndt sandbox fix defer

bq/bq_test.go, bq/insert.go, cmd/etl_worker/etl_worker.go, etl/etl.go, fake/uploader.go, parser/disco_test.go, parser/ndt_test.go, parser/ss.go
This PR:
1. Adapts BQInserter.Flush to FlushSlice, and adds support for asynchronous flushing.
2. Adds FlushAsync() which executes the BQ flush in a goroutine.
3. Add BQInserter.AddRow(), which adds a row without flushing.
4. Updates SS parser to use AddRow(), and FlushAsync()
5. Updates and improves unit tests.
6. Tweaks organization of BQInserter fields.
7. Tweaks parameters in test case BQInserters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/523)
=> Ndt sandbox async flush cleanup

bq/bq_test.go, bq/insert.go, etl/etl.go, parser/ndt_test.go, parser/ss.go
Add support to BQInserter for external buffering.  (Also removes the row buffer and AddRow and FlushAsync, as those will now be handled outside BQInserter)
This is required to support batch annotation, so that the parser can accumulate rows, then annotate them, then uploader.Put them to bigquery.
This is done on top of vet-ss branch.  Don't review ss.go cleanup of hyphenated var names, as those diffs will disappear when vet-ss is committed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/525)
=> Batch ann 1

parser/disco_test.go, parser/ndt_test.go, parser/ss.go, parser/ss_test.go
Switch sidestream over to use local row buffer, and annotate all rows in a batch annotation call, prior to sending to inserter.
Also adds some missing error checking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/527)
=> use batch annotation for ss.go

parser/disco.go, parser/disco_test.go, schema/switch_schema.go
This change is a companion to https://github.com/m-lab/etl-schema/pull/5
This change updates the disco switch schema to use standard columns for `test_id`, `task_filename` and `parse_time`.
As well, this change should resolve https://github.com/m-lab/etl/issues/462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/530)
=> Use standard columns for switch schema

.travis.yml
We want to process ALL sidestream data as it comes in.  This PR adds cloud functions on the embargo bucket, so that both the archive bucket and the embargo bucket notifications trigger the pipeline.
Used **gsutil notification list gs://embargo-mlab-oti** to ensure that there was not already a notification registered.
This method also allows us to monitor whether all data is being handled properly by the embargo process, and to distinguish easily in BQ whether rows should be visible to the public.
Note: This also adds the ndt-prod deployment trigger to the production cloud function deployment section, so that cloud functions will be deployed any time NDT is deployed.  They are NOT auto-deployed with the small-prod trigger.  This is intentional, so that we don't accidentally impact NDT …
=> Add cloud function trigger to embargo buckets

parser/disco.go, parser/disco_test.go
This change adds a condition to check whether the `tmp.Sample` contains at least one element.
While `Sample` should normally have a length greater than zero, evidently during the roll out of the pause frame collection there was one export hour that included the "pause" frame metrics but without any samples (b/c they had not been collected yet).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/541)
=> Verify that Sample length is non-zero

.travis.yml, functions/enqueue.js
Turns out that cloud functions deployment don't work properly without this flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/540)
=> add trigger-event

parser/ndt.go, parser/pt.go, parser/pt_test.go, parser/ss.go, schema/pt_schema.go, schema/ss_schema.go
In service of https://github.com/m-lab/etl/issues/285 and following https://github.com/m-lab/etl-schema/pull/7 this change adds new logic to set standard column values in NDT and Paris Traceroute parsers.
With this change:
* NDT will set the parser_version column.
* Paris-Traceroute will set the parser_version and parse_time columns, with task_filename left as a TODO.
As well, this change includes minor variable name changes in the SS and PTR parsers to use Go naming conventions. i.e. Test_id -> TestID. These changes should have no effect on output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/552)
=> Update ETL parsers with standard columns

parser/pt.go, parser/pt_test.go
Add new field to track and populate the taskFileName in paris-traceroute parser.
This should complete https://github.com/m-lab/etl/issues/285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/553)
=> Populate paris-traceroute task_filename

.travis.yml, cmd/etl_worker/app-batch.yaml, etl/globals.go
Now that the batch parser is generic, rename the environment variable used to tell the parser that it is batch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/557)
=> Use generic BATCH_SERVICE env to tell parser it is batch

schema/pt_schema.go, schema/ss_schema.go
Evidently, without explicit `bigquery` tagging on field names, bigquery uses an automated conversion that is incompatible with the schema changed in https://github.com/m-lab/etl/pull/552
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/559)
=> Update schemas with explicit bigquery tags

functions/embargo/transfer.js
This change updates the embargo criteria in `shouldEmbargo` to unconditionally return false.
The consequence of this change is that the sidestream archives will be copied, unmodified from scraper-<project> to archive-<project> just like all other files.
This change also preserves the embargo frame work in case we want to add new experiments to it in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/564)
=> Unconitionally return false for "shouldEmbargo"

.travis.yml
This change updates travis.yml to use 'master' as the default branch for staging deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/568)
=> Update travis.yml to use "master" branch

appengine/queue_pusher/queue_pusher.go, cmd/etl_worker/etl_worker.go, etl/globals.go, etl/globals_test.go, metrics/metrics.go, metrics/metrics_test.go, storage/storage.go
queue_pusher imports github.com/m-lab/etl/etl and github.com/m-lab/etl/storage.
Both packages import metrics, which imports the prometheus client libraries
which now include `syscall` imports, which are forbidden in AppEngine SE. As a
result the queue_pusher build fails.
This change moves etl.CountPanic to `metrics`, since this seemed like the next logical place.
This change moves storage.GetFilename to etl globals.go and adds a unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/570)
=> Remove prometheus client from etl & queue_pusher dependencies

.travis.yml
This change fixes a typo (no idea how I missed it) for INJECTED_PROJECT for sidestream parser in mlab-oti.
Currently etl-sidestream-parser is writing to tables in mlab-oti instead of measurement-lab.
This only affects the daily pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/572)
=> Correct typo on INJECTED_PROJECT for sidestream

appengine/queue.yaml, cmd/etl_worker/app-batch.yaml
Adjust the queue parameters to better balance ndt/switch/sidestream processing rates.
Increase batch pipeline to 50 instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/574)
=> Rebalance batch queues

appengine/queue.yaml
Disco is still running more than 3x as fast as required.  This slows it down by 60%, which should allow other data types to run a little faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/575)
=> slow down disco queues

.gitmodules, .travis.yml
This change adds sync_tables_with_schema.sh to the relevant sections for all etl deployments. This change also adds the etl-schema repo as a submodule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/578)
=> Add sync_tables_with_schema.sh to deployements

cmd/etl_worker/app-batch.yaml
We are having some stability problems around 150 instances in sandbox.  Staging seems to be working ok with 250 instances, though we are hitting bigquery streaming quota caps.  Staging is running etl commit 37639eb, with 250 instances, but with modest throughput, with only about 3 or 4 workers per instance active.  So that probably accounts for the better stability.  Not clear why the number of workers is lower.
Anyhow, this PR changes the max instances to 100.  When we have worked out the scaling kinks, we can gradually increase the max again.
This PR does NOT changes the task queue configs, so the queues will likely max out the workers, and cause high task rejection rates from the pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> reduce max instances to 100

annotation/geo.go
This change reduces label noise from the AnnotationErrorCount metric and logs the error.
Fixes: https://github.com/m-lab/etl/issues/586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/587)
=> Use static metric label for annotator post errors

annotation/geo.go, annotation/geo_test.go, parser/geo_annotation.go, parser/geo_annotation_test.go
ETL code currently depends on GeoLocationIP field names, instead of json tags.
This fixes that, so that we can use common annotation-service/api/api.go in next PR.
See #593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/594)
=> Use tags for map names

annotation/geo.go, annotation/geo_test.go, parser/geo_annotation.go, parser/geo_annotation_test.go, parser/ndt.go, parser/pt.go, parser/ss.go, schema/pt_schema.go, schema/ss_schema.go
Now that json tags are respected, we can switch to the annotator/api structs.
This also removes the EnableAnnotation, since we haven't used it in over a year.
(HMM - need to check with Stephen about disco, which has annotation disabled.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/596)
=> Use annotator structs

annotation/export_test.go, annotation/geo.go, annotation/geo_test.go, parser/geo_annotation_test.go
I've created a GetAnnotations function in annotation-service/api/v2 that wraps the http request and retries on ServiceUnavailable failures.  This keeps more of the repo specific code in the same annotation-service repo, though it does require a recompile of ETL to get new changes.
One question this raises - should we use dep to vendor the specific version of annotation-service used?  This is demonstrated in the batch-sandbox-retry-v2 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/600)
=> Use the new annotation-service/api.GetAnnotations

annotation/geo.go
See Bug #602
This PR just adds a 2 minute timeout to the GetAnnotations context.  This may be too long.  Probably 30 seconds would be better, since annotators usually take less than 20 seconds to load, and loading is the primary (or possibly) only cause of retry loops.
This DOES NOT resolve the bug, as there is some other reason on the annotator side that the annotator was never being loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/603)
=> add annotation timeout

annotation/geo.go
This is producing too many unique error types, spamming Prometheus!!
Started Jan 7, 16:27 UTC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/605)
=> avoid spam in metric

.travis.yml, appengine/queue.yaml
This tweaks the queues to make sidestream run slower, and ndt run faster.
Also adds a tq target, so we can adjust the queues in sandbox without restarting batch pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/607)
=> Tq sandbox faster ndt

parser/geo_annotation.go, parser/geo_annotation_test.go, parser/ss.go
Merge #524 included commenting out this AddGeoData...().  Merge #527 replaced this with batch annotation, so this commented code is obsolete since then.
This cleans that up so we won't be mislead in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/609)
=> Replace commented code with historical comment

annotation/geo.go
Used an out of date example.  This uses the correct semantics (for the return values).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/608)
=> function vs file

cmd/etl_worker/app-batch.yaml, cmd/etl_worker/app-disco.yaml, cmd/etl_worker/app-traceroute.yaml
We are seeing frequent OOMs in etl-batch-parser in prod.
This increases memory to 6GB, which will likely resolve the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/611)
=> more memory to prevent oom

annotation/geo.go, parser/geo_annotation.go, parser/geo_annotation_test.go
This updates NDT to use FetchAnnotations, which in turn uses the v2 annotation-service API.
This provided better metrics in etl, and reduces the number of code paths in annotation-service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/619)
=> Update ndt to use v2 annotator API

appengine/queue.yaml
Sidestream is currently taking about 3X as long (in prod) as ndt and disco to process the full backlog.
So this once again tweaks the concurrent tasks to try to align the gardener throughput a bit better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/630)
=> sidestream 50% faster

.travis.yml
This change removes the INJECTED_PROJECT from the production deployment of the daily ETL parsers.
As a result, the daily parsers will write to the project-local dataset.
Shortly after this change is deployed to production, we should also deploy https://github.com/m-lab/etl-schema/pull/25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/638)
=> Production daily parsers will write to project-local datasets

parser/base.go, parser/base_test.go
This adds several refinements:
1.  Rename GeoData to Annotations, and add alias for backward compatibility.
2.  Add Annotator interface, and support injection of Annotator into parser.Base.
3.  Tweak the Annotatable interface to support multiple hops in PT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/658)
=> improve to support injected annotator and PT multiple hops

cmd/etl_worker/etl_worker.go, storage/storage.go, storage/storage_test.go
ETL has been using a deprecated gcloud storage library.  This updates to use the recommended library.
It also incorporates proper handling of timeout cancel for GetStorageObject.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/665)
=> Batch sandbox update storage

schema/tcpinfo.go, schema/tcpinfo_test.go, schema/web100.go
This introduces the go structs for the new tcpinfo table rows.
It includes some rather hacky code for handling the embedded SockID structs for the short term.  I am working on an alternative that substitutes the SockID struct in the ArchivalRecord decoding, but this is the shorter path to getting something running in staging.
Feedback welcome on the overall row schema implied in the structs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/669)
=> Tcpinfo schema

parser/parser.go, parser/tcpinfo.go, parser/tcpinfo_test.go, schema/tcpinfo.go
This adds handling of the etl.TCPINFO type for NewParser, which enables parsing of tcpinfo through the normal request mechanism.
This PR also makes some tweaks to the tcpinfo parser and schema to improve handling of the SockID and ClientInfo and ServerInfo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/673)
=> Enable tcpinfo parsing

etl/globals.go
tcpinfo parser is failing inserts because the buffer is sometimes too big.  This buffers fewer rows to reduce likelihood of that happening.
TODO: should probably also limit the number of snapshots in any given test, to avoid excessively large individual tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/674)
=> Buffer only 10 rows for tcpinfo

appengine/queue.yaml
This change adds two task queues for the tcpinfo batch parser.
Due to the low amount of data currently, we're starting with only two queues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/677)
=> Add tcpinfo batch parsing queues

appengine/queue_pusher/queue_pusher.go, appengine/queue_pusher/queue_pusher_test.go, etl/globals.go, etl/globals_test.go
This fixes the etl/globals.go, and also fixes a logging bug in queue_pusher.go.
Also adds unit test so that we don't miss this next time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/683)
=> Fix regexp to handle traceroute filenames

bq/insert.go, etl/globals.go
Reduces tcpinfo insert buffer to reduce rejected inserts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/680)
=> Decrease insert buffer size for tcpinfo

appengine/queue.yaml, etl/globals.go, parser/ndt_legacy.go, parser/parser.go, schema/ndt_legacy.go
This change adds basic ndt_legacy parser support for the legacy JSON output format from the ndt-server.
Ultimately this functionality should be retired once the ndt-server Result type unifies the legacy & ndt7 schemas. For now, this parser will help with analysis of the data from the new ndt-server pilot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/696)
=> Add parser for NDT legacy format from ndt-server

appengine/queue.yaml
This adjusts the NDT task queue request rate from 10 to 5, to reduce the degree to which NDT is crowding out other tasks.
It also increases ndt-legacy request rate from 0.2 to 1.0.  This may require addition adjustment, but it is difficult to know without trial and error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/698)
=> adjust ndt and ndt-legacy rates

cmd/update-schema/update.go
This is a quick and dirty update/create tool for the tcp-info schema.
For now it only handles tcpinfo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/671)
=> Add update schema tool

appengine/queue.yaml, bq/bq_test.go, bq/insert.go, cmd/etl_worker/etl_worker.go, etl/globals.go, fake/uploader.go
When bigquery encounters "Request payload size exceeds ..." errors, it is often because a single row is too large.  This recursively splits the buffer in half and tries again.  Some rows may still fail, but they won't prevent other rows from successfully inserting.
This should (mostly) resolve #705.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/706)
=> Handle request too big

appengine/queue.yaml, parser/ndt.go, parser/pt.go, parser/tcpinfo.go
tcpinfo processing speed in staging is quite slow, because of data volume.  This speeds it up 5x.
Also adds some missing metrics, and improves metric labels.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/707)
=> add metrics and increase tcpinfo speed

schema/ndt_legacy.go
change from legacy to ndt5 broke etl.
This fixes etl, so that it can build at head.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/711)
=> fix ndt5 dependency

cmd/update-schema/update.go, etl/globals.go, parser/ndt_legacy.go, parser/parser.go, schema/ndt_legacy.go
This change removes support for the ndt "legacy" format for ndt5 results from the Go ndt-server. Instead, a new unified result schema records both ndt5 and ndt7 results. The current ETL worker will only recognize ndt5 results now due to the different directory hierarchy for ndt7 results. As well, this is the first time we've had two datatypes mapped to the same table, so gardener does not yet support ndt7 either. However, from 2019-07-19 forward, all results should use unified schemas.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/714)
=> Update ETL parser to read ndt5 Result

parser/pt.go, parser/pt_test.go
This fixes handling of PT test with no hops.  Previously it was returning an error, but it is not an error to have no hops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/726)
=> fix pt empty hop handling and unit test

parser/pt.go
This will also fix the NDT build
Please submit this immediately if it looks good to you. The ndt-server build is currently broken due to `go vet` complaints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/735)
=> Fix `go vet` field visibility error

appengine/queue.yaml
This increases the number of tcpinfo queues, and max_concurrent jobs per queue, to allow us to speed up tcpinfo processing.
The speedup will also be influences by changes to the other gardener configs, as there will be fewer queues used for ndt and sidestream, freeing up more resources in the etl batch processing instances.
This change must be deployed prior to etl-gardener changes (which include use of the previously non-existent extra tcpinfo queues).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/759)
=> increase tcp-info queues and max_concurrent

appengine/queue.yaml
staging dashboard shows the total concurrent is a little low, so this uses up the available concurrency.  This won't quite double the tcpinfo rate, since the cpu utilization won't change much.  tcpinfo will just get a larger share of the resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/760)
=> 200 max_concurrent tcpinfo

Dockerfile, README.md
This change will adds a new Dockerfile to the m-lab/etl repo. This Dockerfile builds the `generate_schema_docs` container.
Build rules in dockerhub will produce a new version on every `/v.*/` tag of the ETL repo.
Part of https://github.com/m-lab/dev-tracker/issues/472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/761)
=> Add Dockerfile for generate-schema-docs container

.travis.yml, active/active.go, active/active_test.go, active/runnable.go, cloud/gcs/gcs.go, cloud/gcs/gcs_test.go
Implements a source of Runnables backed by a GCS bucket/prefix.
It currently allows injection of the function to fetch the files, but it is not clear if this is needed.
Also allows injection of the a function to create the Runnable, which simplifies testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/770)
=> Filesource

.travis.yml, cmd/etl_worker/app-batch.yaml
#792 problem may be related to individual tar files taking too long, which is a question of resources available to the individual workers.
This attempts to resolve the problem by increasing the number of CPUs, without changing the number of workers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/793)
=> Batch sandbox cpu

cmd/etl_worker/app-batch.yaml
Allow more workers, and lower target cpu, so that appengine will deploy more instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/795)
=> Adjust appengine params

annotation/geo_test.go, parser/base_test.go, parser/ndt_test.go, parser/ss_test.go
Reverts m-lab/etl#825
Evidently some individual etl parsers have dependencies on the json representation of the geo data. I will revert these changes to preserve existing functionality and create mirror structs for use by uuid-annotator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/826)
=> Revert "Update unit tests to use changed Geo field names"

bq/insert.go, parser/pt.go
Improve noisy metrics:
- break out Quota Exceeded
- change pt corrupted content to Warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/833)
=> Batch sandbox noisy metric

bq/insert.go, etl/etl.go, parser/ndt_test.go, parser/parser.go, parser/tcpinfo.go, parser/tcpinfo_test.go, row/row_test.go, schema/schema_test.go, task/task.go
This migrates the tcpinfo parser to use row.Base.
It requires a fair amount of cruft because the rest of the system still expects TCPInfoParser to implement etl.Parser.
This will eventually allow migration to a back end that uses GCS json files, to enable BQ Loads instead of streaming inserts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/835)
=> Implement tcpinfo parser using row.Base

active/poller.go, active/poller_test.go, etl/etl.go, parser/tcpinfo_test.go, schema/tcpinfo_test.go, storage/storage.go, storage/storage_test.go, task/task.go, task/task_test.go, worker/worker.go
This moves struct storage.ETLSource to interface etl.TestSource.   storage.GCSSource implements the interface backed by a GCS object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/845)
=> Refactor ETLSource

bq/insert.go, parser/tcpinfo.go, parser/tcpinfo_test.go, row/row.go, row/row_test.go
This makes some improvements to Stats to make future integration with BQInserter easier.
It creates ActiveStats which wraps a Stats object, and handles all updates.
It updates BQInserter to return the count of rows successfully inserted, which is then used by row.Base to do accounting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/848)
=> row.Stats improvements

parser/ndt_result.go, parser/ndt_result_test.go, parser/parser.go, parser/tcpinfo.go, parser/tcpinfo_test.go, row/row.go, schema/ndt_result.go
Previous PR refactored BQInserter to support row.Base stats.
This migrates NDTResultParser to use row.Base, allowing later substitution of GCS Sink.
This also seems to slightly reduce the memory footprint, which is unexpected.  May just be that it hasn't run long enough to reach the peak memory use.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/849)
=> Migrate ndt_result to use row.Base.

.travis.yml, apply-cluster.sh, k8s/data-processing/deployments/parser.yml
This configures the GKE parsers to write to templated tables in ndt_raw.  Next step is to make them write to normal partitioned tables.
Manually created the tables in sandbox.  The creation query is in the Description fields.
I had to change the ndt5 log_time field to be a timestamp to allow column partitioning.  
This change has NO impact on V1 parser - only V2 GKE instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/852)
=> Add BIGQUERY_DATASET for GKE deploymment

parser/ndt7_result.go, parser/ndt7_result_test.go
This change fixes the calculation for rate used by the etl ndt7 parser. BytesSent includes retransmissions, while BytesAcked includes only the bytes received by the client, more closely reflecting user experience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/856)
=> ndt7: Use BytesAcked to calculate MeanThroughputMbps

parser/ndt7_result.go
This fixes a bug in the ndt7 parser `IsParsable` to recognize `.json.gz` files which is the typical output format for ndt7 datatype.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/861)
=> Allow json.gz files for ndt7

cmd/etl_worker/etl_worker.go, parser/ndt7_result.go
This change really fixes the is parsable bug for ndt7. This also adds flag parsing to the etl_worker to begin using logx.Debug logs in some places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/862)
=> Fix IsParsable again

cmd/etl_worker/etl_worker.go, etl/globals.go, metrics/metrics.go, metrics/metrics_test.go, task/task.go, worker/worker.go, worker/worker_test.go
This uses the new factories to provide context for task creation in ProcessGKETask.
This also simplifies and regularizes the labels in TaskCount, which were particularly ugly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/870)
=> inject task.Factory into ProcessGKETask

active/active.go, active/active_test.go, active/poller.go, cloud/gcs/gcs.go, cloud/gcs/gcs_test.go
This plumbs through the archive filter from the job service.  This allows selectively processing a subset of the archive files, on the basis of an archive path regular expression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/879)
=> Implement archive filter

.travis.yml
This will reduce interference between development on new and old parser features.
Also makes .travis.yml "go get" and goveralls more robust.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/885)
=> Deploy sandbox k8s parsers only on u-sandbox branches

cmd/update-schema/update.go
During the GCEE incident, redeploying the ETL batch parsers caused a new ndt5 schema in the parser that was not updated in the underlying batch and base_tables.
After manually restoring the ndt5 schemas in https://github.com/m-lab/dev-tracker/issues/597 this change restores "ndt5" steps in update-schema.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/890)
=> Restore ndt5 schema updates

.travis.yml
Bad syntax in a deployment condition was causing unconditional deployment on all travis builds, leading to deployment failures.
Argh!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/891)
=> fix bad deployment condition

.travis.yml, etl/etl.go, parser/annotation.go, parser/annotation_test.go, parser/ndt7_result.go, parser/ndt7_result_test.go, parser/tcpinfo_test.go, storage/storage.go, storage/storage_test.go, task/task.go, worker/worker.go
This change updates the source of the row.Date value from the measurement StartTime to the GCS path date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/896)
=> Use GCS archive path date for row.Date

Dockerfile
Previously, the generate-schema-docs image was failing with errors like:
```
github.com/m-lab/ndt-server/bbr
../ndt-server/bbr/bbr.go:18:9: undefined: enableBBR
../ndt-server/bbr/bbr.go:23:9: undefined: getMaxBandwidthAndMinRTT
```
This turned out to be due to `CGO_ENABLED=0`, removing this requires that the build env and final env use the same base image, so that the few dynamic linked libraries match exactly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/903)
=> Build and ship in same environment

parser/tcpinfo_test.go, storage/storage.go, storage/storage_test.go, task/task.go, task/task_test.go, worker/worker.go, worker/worker_test.go
When we move to GCS json output, we need to be able to terminate parsing if there is a write error.
This also migrates some APIs to use stiface.Client to allow future injection of fakes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/906)
=> Add Fail fast option in ProcessAll, so that file write errors can be fatal.

active/poller.go, cmd/etl_worker/etl_worker.go, cmd/etl_worker/etl_worker_test.go, k8s/data-processing/deployments/parser.yml
1. Refactor main to make use of mainCtx, and make server setup clearer.
2. Unifies env and flags.
3. Add etl_worker_test to unit test parts of main.
4. Add Gardener info to status page
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/911)
=> refactor main, unit test, more status info

active/active_test.go, active/poller.go, active/runnable.go, active/throttle.go, active/throttle_test.go, cmd/etl_worker/etl_worker.go, worker/worker.go, worker/worker_test.go
A bug due to passing nil context was exposed yesterday.  Not sure why it seemed to work before.
This adds context to parameters where it is needed for Run().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/919)
=> add ctx to Run()

active/poller.go, cmd/etl_worker/etl_worker.go
This adds a command line flag to control whether parsing writes to GCS json files, or to BigQuery streaming API.
Also adds gardener related detail to status page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/920)
=> conditional json output and enhanced status

parser/disco.go
The rewritten DISCO outputs the same format at the old "utilization" experiment, but names the files with a suffix of `jsonl` instead of just `json`, since it is rightly JSONL. This PR just fixes to the parse to recognize files with a `jsonl` suffix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/922)
=> Accepts JSON and JSONL suffixes for test filenames.

k8s/data-processing/deployments/parser.yml, parser/ndt7_result.go
This enables output to GCS for the K8S parsers.  It does not impact the legacy parsing pipeline.
It also:
1.  Adds handling of ndt7 ConnectionInfo fields, that were previously suppressed using a bigquery tag.
2.  Reduces the max tasks to 100, as 200 seems to be unnecessarily high.  There is modest loss of CPU utilization, but same or better throughput, suggesting there was some thrashing at 200.
Before merging this, we should also:
1. Create the etl-mlab-staging bucket.
2. Have the gardener PR ready to merge that handle loading of data from GCS.  The old gardener will still drive reprocessing, but will not load the data from GCS, so tables won't actually get updated, and will likely be overwritten with empty partitions.
---
This change is [<img …
=> Enable GCS json output

k8s/data-processing/deployments/parser.yml
This reduces the cpu resource request to 7 cpus, for two reasons...
1.  This will be more than adequate for the short term.
2.  It will allow mapping the pods onto a new node-pool "parser-pool" with different scopes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/925)
=> k8s config to use 7 cpus, to allow mapping to "parser-pool"

.travis.yml, appengine/queue_pusher/queue_pusher_test.go, cmd/update-schema/update.go
This mostly improves readability in .travis file for updating a subset of the schemas, corresponding to the Gardener v1 or v2 data types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/935)
=> Add standard and legacy update-schema types

storage/rowwriter.go
This will allow future use of the meta-data by gardener to ensure that the data has been correctly parsed and loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/937)
=> Add row count and error meta-data to json output files

parser/ndt7_result.go, parser/ndt7_result_test.go
Network researchers expect RTT to be in milliseconds. This change restores the MinRTT unit in the summary table to use `ms`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/938)
=> Use milliseconds not seconds

.travis.yml, cmd/update-schema/update.go, schema/switch_schema.go
DISCOv2 now includes a `counter` field in every sample, which records the raw counter value for the OID at the time of the sample, instead of just the from the previous raw counter. This should allow us to validate the data in various ways.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/951)
=> Add new field Counter to switch schema.

parser/disco.go
DISCOv1 sample timestamps represent the start/beginning of a 10s sample window, while v2 timestamps represent the end of a 10s sample window. Since the v2 behavior is more logical, for consistency, this PR adds 10s to all v1 sample timestamps so that they should match the *end* of the sample window, not the beginning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/954)
=> Adds 10s to all v1 sample timestamps so that DISCOv1 matches DISCOv2-style timestamps

schema/ndt5_result.go
The ndt7 schema does not include the server and client annotation fields because these fields are defined by the materialized join managed by etl-gardener.
This change removes the empty fields from the ndt5 schema because this data type should be managed like ndt7 wrt annotations.
Annotations pre-2020-03 will be exported by the annotation service to the annotation tables as part of future work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/963)
=> Remove client and server annotations from ndt5 schema

cmd/etl_worker/app-batch.yaml
The current AE batch parser instances are over saturated and task queues are timing out.
This change increases the max number of instances using the current etl-gardener queue settings (which are almost as low as they can go without turning any datatypes off).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/964)
=> Increase max instances

.travis.yml, annotation/geo.go, bq/bq_test.go, cmd/etl_worker/Dockerfile.k8s, cmd/etl_worker/etl_worker.go, cmd/etl_worker/etl_worker_test.go, etl/globals.go, etl/globals_test.go, metrics/metrics.go, parser/base_test.go, parser/ndt.go, parser/parser.go, parser/parser_test.go, parser/ss_test.go, parser/tcpinfo_test.go
This change prepares for migration of the ETL build and deployment to cloudbuild, the first of two changes.
This change removes use of `os.Getenv` and `os.LookupEnv` throughout the sources in favor of flags that can be set using environment variables. In particular, this makes the `GitCommit` and `Version` variables set at build time, instead of reading them from the environment. In several other cases, this change means using global package variables until code is improved to set a "config" struct to pass around for access to these runtime flags.
NOTE: once this change is merged, the 'Version' will not be set correctly in mlab-staging for the universal gardener by the existing cloudbuild of the Dockerfile. The second change that completes the CB migration is ready and will resolve this. …
=> Prepare for cloudbuild migration 1 of 2

.travis.yml, Dockerfile.testing, apply-cluster.sh, bq/bq_test.go, bq/gke_test.go, cloudbuild.yaml, cmd/etl_worker/Dockerfile.k8s, cmd/etl_worker/app-batch.yaml, cmd/etl_worker/etl_worker_test.go, integration-testing.sh, k8s/data-processing/deployments/parser.yml, storage/storage_test.go, worker/worker_test.go
This change completes the migration to cloudbuild started in https://github.com/m-lab/etl/pull/972
This change requires new Cloud Build trigger configurations and environment variables for deployment to data-processing cluster.
* _CLUSTER - the dat-processing cluster name
* _CLUSTER_REGION - the data-processing cluster region
* _DOCKER_TAG - the docker tag variable ($COMMIT_SHA in sandbox and staging, $TAG_NAME in mlab-oti)
* _SERVICE_ACCOUNT_MLAB_TESTING - the mlab-testing SA used for integration tests.
This change adds new files:
* Dockerfile.testing - used for unit testing Go sources from CB
* cloudbuild.yaml - used for performing the cloud build
* integration-testing.sh - used for running integration tests in travis and CB.
This change correctly adds some unit tests files to the …
=> Complete etl deployment migration to cloudbuild.yaml 2 of 2

parser/pt_test.go
This PR improves test function names in pt_test.go to better
indicate the package functions they are testing.
The changes were tested as follows:
$ git status -s
$ go test ./...
$ git status -s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/975)
=> Improve package test function names

go.mod, go.sum
This just removes the etl-schema submodule.
Testing:
Check for references:
find . -type f | xargs grep sync_tables
find . -type f | xargs grep m-lab/etl-schema
(There are still some references in .git/modules but those are local files)
Run unit tests.
Verify build https://pantheon.corp.google.com/cloud-build/builds;region=global/1de36a06-955f-4ee9-9429-52e3a02bc060?project=mlab-sandbox
Confirm operation in sandbox:   https://cloudlogging.app.goo.gl/6h8L3DJccr2i8Cvv7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/979)
=> remove etl-schema submodule

k8s/data-processing/deployments/parser.yml
The 2.0 parsers are running on 16 cpu machines, but only using 7 cpus.  This allocates 15 cpus, which improves throughput and utilization, but also increases GCS and BQ costs by a very modest amount.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/981)
=> Adjust K8S parsers to use 15 cpus

cmd/update-schema/update.go, schema/ndt_web100.go
This change adds a new Go struct that mirrors the current ndt web100 schema.
Notable differences:
* `Deltas` reuses the `web100Snap` structure, which includes LocalAddress, RemAddress, and related fields that are not found in the current schema. This difference simplifies the structure without duplicating all other fields.
* Adding `api.ASData` to the client and server network information to mirror annotation-service values.
* Adding `api.GeolocationIP` for the client and server geolocation to mirror annotation-service values.
* Server geolocation does not include "Machine" and "Site" fields used in the uuid-annotator.
I accidentally updated part of the `mlab-sandbox.base_tables.ndt` table during testing of `update-schema` so the extra columns noted above are already present in the …
=> Add NDTWeb100 struct to mirror current BQ schema

cmd/etl_worker/etl_worker.go, storage/localwriter.go, storage/localwriter_test.go
This change adds a new output mode to the ETL worker (aka parser) to support writing to local files. The `storage.LocalWriter` type implements the `row.Sink` interface. With this change there are now three output modes: "bigquery" (direct, original mode), "gcs" (for bq loads from gcs), "local" (new, added for local development).
The "local" output mode wites files like "gcs" mode (i.e. JSONL named after the archive) but to a local directory specified with the new `-output_dir` flag.
The LocalWriter is expected to help simplify local development of the etl worker, e.g. for a new datatype by removing some dependencies on BigQuery, table schemas, and updates.
Tested using unit tests and running locally using:
```
~/bin/etl_worker -prometheusx.listen-address :9991 -service_port :8081 …
```
=> Add support for storage.LocalWriter

etl/globals.go, etl/globals_test.go, storage/export_test.go, storage/localwriter.go, storage/localwriter_test.go, storage/rowwriter.go, storage/rowwriter_test.go, storage/storage.go
This change adds a new helper method to recover the GCS "Path" portion of the URI. A common use case is extracting this path. As a result, this change reduces some ad-hoc parsing of the URI in favor of placing all URI parsing in the etl.DataPath type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/993)
=> Add method for GCS Path for DataPath type

README.md, cmd/etl_worker/etl_worker.go, cmd/etl_worker/etl_worker_test.go, go.mod, go.sum
This change adds a new handler to the passive mode ETL worker to support v2 datatypes including during local development.
This change adds a new resource, `/v2/worker`, that is unconditionally available when the worker is started.
The `/v2/worker` handler accepts a `filename=` parameter (like the existing `/worker` handler used by the legacy pipeline). However, the `/v2/worker` only supports v2 datatypes.
With this handler, a developer can run the worker in "local" output mode to test behavior of a new parser without depending on BigQuery or other GCP services (other than the source archive in GCS). This handler also allows adhoc tests in GKE.
Instructions for use are now included in the README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Add handler for local output mode

go.mod, go.sum
Include fix from https://github.com/m-lab/annotation-service/pull/289 into etl.
This change allows server annotations from siteinfo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/997)
=> Update annotation-service version to include fix

go.mod, go.sum, parser/ndt.go, parser/ndt_test.go, schema/ndt_web100.go, schema/web100.go
This change adds two new fields to the ndt.web100 schema and parser. The ServerX and ClientX fields are exact copies of the uuid-annotator structures populated with the results from the annotation-service.
This change should make annotation export queries simpler because whole records can be used in the result as-is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/999)
=> Add ServerX and ClientX annotation fields to ndt.web100 schema and parser

parser/ss_test.go, schema/sidestream_schema.go
This change updates the sidestream schema with the same fields added to the ndt.web100 schema in https://github.com/m-lab/etl/pull/999
The ServerX and ClientX fields are exact copies of the uuid-annotator structures populated with the results from the annotation-service. This change should make annotation export queries simpler because whole records can be used in the result as-is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1000)
=> Add ServerX and ClientX annotation fields to sidestream schema and parser

parser/ss.go, web100/parse.go, web100/parse_test.go
This change fixes the triple-colon formatting in sidestream IPv6 addresses.
Around 2.7B rows in sidestream include `:::` in the remote or local IP.
```
web100_log_entry.connection_spec.remote_ip LIKE '%:::%' OR web100_log_entry.connection_spec.local_ip LIKE '%:::%'
```
This change uses a new function `NormalizeIP` that corrects this formatting. If the IP address is invalid for other reasons, it will be used as-is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1001)
=> Apply NormalizeIP to sidestream addresses during parsing

parser/ndt.go, parser/ndt_test.go, parser/ss.go, parser/ss_test.go
This change assigns the `Site` and `Machine` fields of the `ServerX` server annotation record for the sidestream and ndt.web100 datatypes. This change will make the annotation export queries simpler b/c the values can be used as-is rather than re-calculated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1003)
=> Set ServerX fields for Site and Machine

go.mod, go.sum, parser/pt.go, parser/tcpinfo.go, schema/pt_schema.go, schema/tcpinfo.go
This change continues changes to prepare for the annotation export process. This change adds the ServerX and ClientX records to the tcpinfo and traceroute schemas to support the annotation export process by simplifying the export query by using the uuid-annotator schema directly (rather than requiring the query to perform a complex translation at export time).
This change completes all known dependencies for sidestream, ndt.web100, traceroute, and tcpinfo annotation export.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1004)
=> Add ServerX and ClientX annotation records to tcpinfo and traceroute schemas

parser/annotation.go, parser/annotation_test.go, parser/export_test.go, parser/ndt7_result.go, parser/ndt7_result_test.go, parser/parser.go, parser/parser_test.go, schema/schema.go
Summary:
Adding GitCommit field to ParseInfo struct
Description:
This struct is used by NDT7 and Annotation
NDT5 uses another version called ParseInfoV0, so it's not in scope for this change
Testing:
Change includes unit tests and will also be tested by checking the table schema
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1005)
=> Add parser.GitCommit field into ParseInfo struct

parser/ndt.go, parser/parser_test.go, parser/pt.go, parser/pt_test.go, parser/ss.go, parser/tcpinfo.go, parser/tcpinfo_test.go
This change completes the unit tests omitted from https://github.com/m-lab/etl/pull/1004
This change moves the `fakeAnnotator` type from the tcpinfo_test.go file to the common parser_test.go for use by multiple parsers.
This change adds ServerX and ClientX value tests to the tcpinfo parser.
This change adds ServerX and ClientX value tests to the pt parser for .paris and .jsonl file types.
Because correct annotations require well formatted archive URLs, additional changes ensure that valid URLs are provided to unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1007)
=> Complete unit tests for ServerX and ClientX records in tcpinfo and pt parsers

cmd/generate_schema_docs/main.go, cmd/generate_schema_docs/main_test.go, cmd/update-schema/update.go, schema/descriptions/PCAPRow.yaml, schema/descriptions/toplevel.yaml, schema/pcap.go, schema/pcap_test.go
- Added new pcap datatype definition to [m-lab/etl/schema](https://github.com/m-lab/etl/tree/master/schema)
- Added pcap table creation to [update-schema](https://github.com/m-lab/etl/tree/master/cmd/update-schema)
- Added descriptions for PCAPRow schema
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1009)
=> Add schema for pcap index

k8s/data-processing/deployments/parser.yml
Increased the number of parser instances to better handle the amount of data introduced by the PCAP datatype
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1013)
=> Increase number of parser replicas to 6

active/active.go, active/active_test.go, active/poller.go, etl/globals.go, etl/globals_test.go
Update pcap parser to process fewer archives (i.e., 1 in 10)
A similar concept exists in the legacy pipeline with the TASK_FILE_SKIP setting (e.g., https://github.com/m-lab/etl-gardener/blob/master/k8s/data-processing-cluster/deployments/etl-gardener-ndt.yml#L52)
Testing comparing the processing the logs to the archive entries
Log
https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22mlab-sandbox%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.cluster_name%3D%22data-processing%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Frun%3D%22etl-parser%22%20severity%3E%3DDEFAULT;timeRange=2021-08-12T17:13:17.000Z%2F2021-08-12T17:13:18.000Z;cursorTimestamp=2021-08-12T17:13:17.602104577Z?project= …
=> Update pcap parser processing rate to 1 in 10 archives

parser/tcpinfo.go, parser/tcpinfo_test.go
Somehow missed this field for all this time.
Adds a unit test and code to populate the field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1017)
=> add missing filename to ParseInfo for tcpinfo

k8s/data-processing/deployments/parser.yml
Since the PCAP processing rate has been reduced to 10%, we should also decrease the number of parsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1018)
=> Decrease number of parser replicas to 4

README.md, cmd/etl_worker/etl_worker.go, storage/localwriter.go
1.  Add a comment in etl_worker about default application credentials.
?? Should this just be in the README instead?
2. Remove the append option for local output, so that it overwrites instead of appending.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1027)
=> Tweak local mode

etl/globals.go, etl/globals_test.go
This change updates the etl archive path parsing regular expression so that it will match the third-party archives generated by the synthetic uuid annotation export process. The synthetic archives reuse the "machine" field (normally `mlab[1-4]`) and the "site" field (normally `[a-z]{3}\d[0-9t]`) to also match "third" and "party" respectively.
With this change, thirdparty archives copied to the public archive will be natively parseable by the etl+gardener system.
For example:
```
gs://archive-mlab-sandbox/ndt/annotation/2019/07/12/20211107T143543.161376Z-annotation-third-party-ndt.tgz
```
Tested using the local output mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1029)
=> Allow parsing third-party archives

cmd/etl_worker/etl_worker.go, cmd/update-schema/update.go, metrics/metrics.go, metrics/metrics_test.go, task/task.go, worker/worker.go, worker/worker_test.go
Rename the `etl_task_count` metric to `etl_task_total` to honor prometheus best practices for metric naming: https://prometheus.io/docs/practices/naming/.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1040)
=> Rename metric to etl_task_total

cloudbuild.yaml, delete-appengine.sh
AppEngine has a hard limit of 210 service versions across a project. This change adds a small script that deletes all service versions after the first 9 that are non-serving. The number of older versions to preserve is arbitrary; more than 1 to allow rollbacks is the main intention. 9 is conservative number. This change was inspired by an alert in staging about there being too many service versions.
Limitations / caveats:
- The first time this script runs, it will delete many older versions and will take longer than steady state. At the limit, it should delete no more than one per service.
- This script applies to all app engine services but will only run on ETL deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add script to delete extra appengine services

cmd/etl_worker/etl_worker.go, cmd/etl_worker/etl_worker_test.go, k8s/data-processing/deployments/parser.yml
This change changes the `-gardener_host` flag to `-gardener_addr` to allow the caller to specify a host:port combination, typical of Go addresses. This change is a complement to https://github.com/m-lab/etl-gardener/pull/371 which allows gardener to specify the serving port. These changes should allow more flexibility in running the gardener and parser in local development modes and normalizing how addresses are specified in the etl pipeline.
This change additionally updates the k8s configuration that depends on the `GARDENER_ADDR` to specify both the address and port for the Gardener service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1055)
=> Update the gardener_addr flag (2 of 2)

Dockerfile, cmd/etl_worker/Dockerfile.k8s
A lot the project's dependencies were upgraded when we updated to the latest version of ndt-server #1056.
This has caused the Docker build to fail since it some of the new dependencies require a higher version of Go.
https://hub.docker.com/repository/registry-1.docker.io/measurementlab/generate-schema-docs/builds/5dba9aee-3d0c-41b0-90e3-2166e489bb19.
Upgrading the Go/Alpine versions in the Dockerfile to be the same as ndt-server fixes this issue https://github.com/m-lab/ndt-server/pull/339.
Tested locally with `docker build . -t etl`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1058)
=> Update Go version in Dockerfile

schema/descriptions/NDT5ResultRowV2.yaml, schema/descriptions/NDT7ResultRow.yaml
While preparing to update the website documentation for the v2 schema of ndt5, I found that the server metadata fields could use a helpful description. This change adds a description of these fields for ndt5 and ndt7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1063)
=> Add descriptions of server metadata to ndt5 and ndt7

cmd/generate_schema_docs/main.go, cmd/generate_schema_docs/main_test.go, schema/descriptions/Scamper1Row.yaml, schema/descriptions/toplevel.yaml
This change removes support for the older ndt5 schema in favor of the ndt5 v2 schema in `generate_schema_docs`.
With this change, I've removed `parser.*` field definitions from the `Scamper1Row.yaml` and moved them to the `toplevel.yaml` so the descriptions can be shared by all datatypes with a v2 `parser` record.
Part of:
* https://github.com/m-lab/etl/issues/1046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1065)
=> Update generate_schema_docs & parser descriptions

schema/descriptions/Scamper1Row.yaml
This commit adds (or updates) descriptions for the fields that
were not covered in https://github.com/m-lab/etl/pull/1057.
Descriptions for raw.{CycleStart,Tracelb,CycleStop} fields are
provided by scamper's author Matthew Luckie.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1064)
=> Add or update field descriptions for scamper1 datatype

k8s/data-processing/deployments/parser.yml
The introduction of the tcpinfo v2 parser has [significantly slowed processing of the v2 pipeline][a]. This change increases the replicas from 4 to 8.
[a]: https://grafana.mlab-staging.measurementlab.net/d/UTgnK-jMz/pipeline-overview?orgId=1&from=now-7d&to=now&var-project=mlab-staging&var-PrometheusDS=Prometheus%20(mlab-staging)&var-LegacyDS=Data%20Proc%20(mlab-staging)&var-Gardener2_DS=Data%20Processing%20(mlab-staging)&var-states=Finishing&var-states=Processing&var-states2=complete&refresh=5m&viewPanel=54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1071)
=> Double parser replicas to process historical archive faster with tcpinfo

factory/factory.go, parser/annotation.go, parser/hopannotation1.go, parser/ndt.go, parser/ndt5_result.go, parser/ndt7_result.go, parser/pcap.go, parser/pt.go, parser/scamper1.go, parser/ss.go, parser/switch.go, parser/tcpinfo.go
This change eliminates dependency on the annotation-service annotator by replacing changing the `DefaultAnnotatorFactory` to unconditionally return a `NullAnnotator` instance, now exported from the `parser` package.
Ultimately, the annotation call outs can be removed from the source entirely.
This change is part of:
* https://github.com/m-lab/etl/issues/1074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1078)
=> Export NullAnnotator for v2 parsers

cmd/etl_worker/etl_worker.go, parser/annotation.go, parser/annotation_test.go, parser/base.go, parser/base_test.go, parser/hopannotation1.go, parser/hopannotation1_test.go, parser/ndt.go, parser/ndt5_result.go, parser/ndt5_result_test.go, parser/ndt7_result.go, parser/ndt7_result_test.go, parser/ndt_test.go, parser/parser.go, parser/pcap.go, parser/pcap_test.go, parser/pt.go, parser/pt_test.go, parser/scamper1.go, parser/scamper1_test.go, parser/ss.go, parser/ss_test.go, parser/switch.go, parser/switch_test.go, parser/tcpinfo.go, parser/tcpinfo_test.go, row/row.go, row/row_test.go, worker/worker.go, worker/worker_test.go
Now that all network and geographic annotations are static, produced either by the uuid-annotator at measurement time, or historical exports from synthetic uuid annotations, there is no longer any need for the real time annotation logic left from the v1 pipeline.
This change removes almost all references to the annotation parameters and interfaces. The `row` package and references to `row.NullAnnotator` in all current schemas remain to be removed in a future PR.
Part of:
* https://github.com/m-lab/etl/issues/1084
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1087)
=> Remove live v1 annotation logic from data pipeline

k8s/data-processing/persistentvolumes/storage-class.yml
GKE v1beta1 is deprecated and clusters with these resources are
blocked from upgrading automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1099)
=> Change v1beta1 to v1 to unblock GKE upgrades

cmd/etl_worker/etl_worker_test.go, storage/localwriter.go, storage/localwriter_test.go, storage/rowwriter.go, worker/worker_test.go
Today, when we [change the archive source bucket](https://github.com/m-lab/etl-gardener/blob/master/config/config.yml#L9-L11) for a datatype in the gardener config, the output data mixes results from two different sources. We can work around this by deleting the bucket directory, but this is slow. Better for them to remain separate.
This change includes the job source bucket in the output path so that the gardener system preserves the separation between the two directories.
Both the parser and gardener must agree on this path. So, this change must be deployed with its companion in etl-gardener https://github.com/m-lab/etl-gardener/pull/407
Part of:
* https://github.com/m-lab/etl-gardener/issues/349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Add job source bucket to output path

parser/export_test.go, parser/tcpinfo.go, parser/tcpinfo_test.go
This change completes fixes the bug reported by @NotSpecial - https://github.com/m-lab/etl/pull/1104 with an update to the unit test to check that every `FinalSnapshot` matches the last snapshot of the raw, thinned snapshots.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1105)
=> Fix thinSnaps

cloudbuild.yaml, cmd/update-schema/update.go
Previously, the `update-schema` utility only supported legacy datatypes and `ndt` sidecars. The command assumed that datasets already existed. And the logic was straight forward but very redundant.
This change adds support to `update-schema` for creating datasets and sidecar tables for alternate experiments. Previous behavior is still available but no longer run by default. Now, the `-standard` and `-legacy` options are independent. We typically do not need to update the legacy tables any longer and the template table iteration is time consuming.
Example usage now includes:
```sh
update-schema -project mlab-sandbox -standard
update-schema -project mlab-sandbox -experiment foobar -sidecars
update-schema -project mlab-sandbox -experiment wehe -datatype scamper1
```
- - -
This change …
=> Support more options for new experiments

schema/ndt5_result.go, schema/ndt5_result_test.go, schema/schema_test.go
This change is a cleanup and removes an obsolete version of the NDT5ResultRow structure, long replaced by the NDT5ResultRowV2 structure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1115)
=> Remove obsolete NDT5ResultRow type definition

.travis.yml, Dockerfile, Dockerfile.testing, cmd/etl_worker/Dockerfile.k8s, go.mod
It also updates the alpine version to 3.18.
Part of https://github.com/m-lab/dev-tracker/issues/771.
Depends on https://github.com/m-lab/etl/pull/1124.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1126)
=> Update go version to 1.20

.travis.yml, parser/ndt5_result.go, parser/ndt5_result_test.go, schema/descriptions/NDT5ResultRowV2.yaml, schema/descriptions/NDT7ResultRow.yaml
This change corrects a bug in the calculation of the summary record for ndt5 MinRTT.
Previously the value was divided by 1000 twice, which unintentionally converted microsecond resolution value to seconds, when milliseconds was intended. 
Addresses https://github.com/m-lab/etl/issues/1094
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1129)
=> Convert MinRTT to milliseconds

cmd/update-schema/update.go, go.mod, go.sum
This PR upgrades to the latest version of [m-lab/go](https://github.com/m-lab/go) to enforce partition filtering for standard tables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/etl/1132)
=> Require a partition filter for standard tables
